<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 One-way ANOVA | Advanced Statistics Remix</title>
  <meta name="description" content="A textbook for advanced statistics" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 One-way ANOVA | Advanced Statistics Remix" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A textbook for advanced statistics" />
  <meta name="github-repo" content="vectrlab/stat-course-pack" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 One-way ANOVA | Advanced Statistics Remix" />
  
  <meta name="twitter:description" content="A textbook for advanced statistics" />
  

<meta name="author" content="David Schuster" />


<meta name="date" content="2021-10-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ttest.html"/>
<link rel="next" href="multiple-comparisons.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Course Pack for Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About this Book</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#attribution"><i class="fa fa-check"></i>Attribution</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i>License</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="statistics-for-research.html"><a href="statistics-for-research.html"><i class="fa fa-check"></i><b>1</b> Statistics for Research</a>
<ul>
<li class="chapter" data-level="1.1" data-path="statistics-for-research.html"><a href="statistics-for-research.html#introduction"><i class="fa fa-check"></i><b>1.1</b> Introduction</a></li>
<li class="chapter" data-level="1.2" data-path="statistics-for-research.html"><a href="statistics-for-research.html#measurement"><i class="fa fa-check"></i><b>1.2</b> Measurement</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="statistics-for-research.html"><a href="statistics-for-research.html#level-of-measurement"><i class="fa fa-check"></i><b>1.2.1</b> Level of Measurement</a></li>
<li class="chapter" data-level="1.2.2" data-path="statistics-for-research.html"><a href="statistics-for-research.html#continuous-or-discrete"><i class="fa fa-check"></i><b>1.2.2</b> Continuous or Discrete</a></li>
<li class="chapter" data-level="1.2.3" data-path="statistics-for-research.html"><a href="statistics-for-research.html#qualitative-or-quantitative"><i class="fa fa-check"></i><b>1.2.3</b> Qualitative or Quantitative</a></li>
<li class="chapter" data-level="1.2.4" data-path="statistics-for-research.html"><a href="statistics-for-research.html#distribution-a-collection-of-our-observations"><i class="fa fa-check"></i><b>1.2.4</b> Distribution: A collection of our observations</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="statistics-for-research.html"><a href="statistics-for-research.html#descriptive-statistics-summarizing-our-observations"><i class="fa fa-check"></i><b>1.3</b> Descriptive Statistics: Summarizing our observations</a></li>
<li class="chapter" data-level="1.4" data-path="statistics-for-research.html"><a href="statistics-for-research.html#inferential-statistics-generalizing-from-our-observations"><i class="fa fa-check"></i><b>1.4</b> Inferential Statistics: Generalizing from our observations</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="statistics-for-research.html"><a href="statistics-for-research.html#populations-and-samples-who-or-what-the-research-is-about"><i class="fa fa-check"></i><b>1.4.1</b> Populations and Samples: Who (or what) the research is about</a></li>
<li class="chapter" data-level="1.4.2" data-path="statistics-for-research.html"><a href="statistics-for-research.html#constructs-provide-the-context"><i class="fa fa-check"></i><b>1.4.2</b> Constructs provide the context</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="statistics-for-research.html"><a href="statistics-for-research.html#the-cautionary-tale-of-simpsons-paradox"><i class="fa fa-check"></i><b>1.5</b> The cautionary tale of Simpson’s paradox</a></li>
<li class="chapter" data-level="1.6" data-path="statistics-for-research.html"><a href="statistics-for-research.html#studydesign"><i class="fa fa-check"></i><b>1.6</b> A brief introduction to research design</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="statistics-for-research.html"><a href="statistics-for-research.html#some-thoughts-about-psychological-measurement"><i class="fa fa-check"></i><b>1.6.1</b> Some thoughts about psychological measurement</a></li>
<li class="chapter" data-level="1.6.2" data-path="statistics-for-research.html"><a href="statistics-for-research.html#operationalisation-defining-your-measurement"><i class="fa fa-check"></i><b>1.6.2</b> Operationalisation: defining your measurement</a></li>
<li class="chapter" data-level="1.6.3" data-path="statistics-for-research.html"><a href="statistics-for-research.html#ivdv"><i class="fa fa-check"></i><b>1.6.3</b> The “role” of variables: predictors and outcomes</a></li>
<li class="chapter" data-level="1.6.4" data-path="statistics-for-research.html"><a href="statistics-for-research.html#researchdesigns"><i class="fa fa-check"></i><b>1.6.4</b> Experimental and non-experimental research</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="statistics-for-research.html"><a href="statistics-for-research.html#causality-research-and-statistics"><i class="fa fa-check"></i><b>1.7</b> Causality, Research, and Statistics</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="statistics-for-research.html"><a href="statistics-for-research.html#experimental-quasi-experimental-and-non-experimental-studies"><i class="fa fa-check"></i><b>1.7.1</b> Experimental, Quasi-Experimental, and Non-Experimental Studies</a></li>
<li class="chapter" data-level="1.7.2" data-path="statistics-for-research.html"><a href="statistics-for-research.html#demonstrating-causality"><i class="fa fa-check"></i><b>1.7.2</b> Demonstrating Causality</a></li>
<li class="chapter" data-level="1.7.3" data-path="statistics-for-research.html"><a href="statistics-for-research.html#statistics-and-causality"><i class="fa fa-check"></i><b>1.7.3</b> Statistics and Causality</a></li>
<li class="chapter" data-level="1.7.4" data-path="statistics-for-research.html"><a href="statistics-for-research.html#validity-and-reliability"><i class="fa fa-check"></i><b>1.7.4</b> Validity and Reliability</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introR.html"><a href="introR.html"><i class="fa fa-check"></i><b>2</b> Getting started with R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introR.html"><a href="introR.html#videos"><i class="fa fa-check"></i><b>2.1</b> Videos</a></li>
<li class="chapter" data-level="2.2" data-path="introR.html"><a href="introR.html#introduction-1"><i class="fa fa-check"></i><b>2.2</b> Introduction</a></li>
<li class="chapter" data-level="2.3" data-path="introR.html"><a href="introR.html#gettingR"><i class="fa fa-check"></i><b>2.3</b> Installing R</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="introR.html"><a href="introR.html#installing-r-on-a-windows-computer"><i class="fa fa-check"></i><b>2.3.1</b> Installing R on a Windows computer</a></li>
<li class="chapter" data-level="2.3.2" data-path="introR.html"><a href="introR.html#installing-r-on-a-mac"><i class="fa fa-check"></i><b>2.3.2</b> Installing R on a Mac</a></li>
<li class="chapter" data-level="2.3.3" data-path="introR.html"><a href="introR.html#installing-r-on-a-linux-computer"><i class="fa fa-check"></i><b>2.3.3</b> Installing R on a Linux computer</a></li>
<li class="chapter" data-level="2.3.4" data-path="introR.html"><a href="introR.html#installingrstudio"><i class="fa fa-check"></i><b>2.3.4</b> Downloading and installing RStudio</a></li>
<li class="chapter" data-level="2.3.5" data-path="introR.html"><a href="introR.html#startingR"><i class="fa fa-check"></i><b>2.3.5</b> Starting up R</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="introR.html"><a href="introR.html#firstcommand"><i class="fa fa-check"></i><b>2.4</b> Typing commands at the R console</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="introR.html"><a href="introR.html#an-important-digression-about-formatting"><i class="fa fa-check"></i><b>2.4.1</b> An important digression about formatting</a></li>
<li class="chapter" data-level="2.4.2" data-path="introR.html"><a href="introR.html#be-very-careful-to-avoid-typos"><i class="fa fa-check"></i><b>2.4.2</b> Be very careful to avoid typos</a></li>
<li class="chapter" data-level="2.4.3" data-path="introR.html"><a href="introR.html#r-is-a-bit-flexible-with-spacing"><i class="fa fa-check"></i><b>2.4.3</b> R is (a bit) flexible with spacing</a></li>
<li class="chapter" data-level="2.4.4" data-path="introR.html"><a href="introR.html#r-can-sometimes-tell-that-youre-not-finished-yet-but-not-often"><i class="fa fa-check"></i><b>2.4.4</b> R can sometimes tell that you’re not finished yet (but not often)</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="introR.html"><a href="introR.html#arithmetic"><i class="fa fa-check"></i><b>2.5</b> Doing simple calculations with R</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="introR.html"><a href="introR.html#adding-subtracting-multiplying-and-dividing"><i class="fa fa-check"></i><b>2.5.1</b> Adding, subtracting, multiplying and dividing</a></li>
<li class="chapter" data-level="2.5.2" data-path="introR.html"><a href="introR.html#taking-powers"><i class="fa fa-check"></i><b>2.5.2</b> Taking powers</a></li>
<li class="chapter" data-level="2.5.3" data-path="introR.html"><a href="introR.html#bedmas"><i class="fa fa-check"></i><b>2.5.3</b> Doing calculations in the right order</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="introR.html"><a href="introR.html#assign"><i class="fa fa-check"></i><b>2.6</b> Storing a number as a variable</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="introR.html"><a href="introR.html#variable-assignment-using---and--"><i class="fa fa-check"></i><b>2.6.1</b> Variable assignment using <code>&lt;-</code> and <code>-&gt;</code></a></li>
<li class="chapter" data-level="2.6.2" data-path="introR.html"><a href="introR.html#doing-calculations-using-variables"><i class="fa fa-check"></i><b>2.6.2</b> Doing calculations using variables</a></li>
<li class="chapter" data-level="2.6.3" data-path="introR.html"><a href="introR.html#rules-and-conventions-for-naming-variables"><i class="fa fa-check"></i><b>2.6.3</b> Rules and conventions for naming variables</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="introR.html"><a href="introR.html#usingfunctions"><i class="fa fa-check"></i><b>2.7</b> Using functions to do calculations</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="introR.html"><a href="introR.html#functionarguments"><i class="fa fa-check"></i><b>2.7.1</b> Function arguments, their names and their defaults</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="introR.html"><a href="introR.html#RStudio1"><i class="fa fa-check"></i><b>2.8</b> Letting RStudio help you with your commands</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="introR.html"><a href="introR.html#autocomplete-using-tab"><i class="fa fa-check"></i><b>2.8.1</b> Autocomplete using “tab”</a></li>
<li class="chapter" data-level="2.8.2" data-path="introR.html"><a href="introR.html#browsing-your-command-history"><i class="fa fa-check"></i><b>2.8.2</b> Browsing your command history</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="introR.html"><a href="introR.html#vectors"><i class="fa fa-check"></i><b>2.9</b> Storing many numbers as a vector</a>
<ul>
<li class="chapter" data-level="2.9.1" data-path="introR.html"><a href="introR.html#creating-a-vector"><i class="fa fa-check"></i><b>2.9.1</b> Creating a vector</a></li>
<li class="chapter" data-level="2.9.2" data-path="introR.html"><a href="introR.html#a-handy-digression"><i class="fa fa-check"></i><b>2.9.2</b> A handy digression</a></li>
<li class="chapter" data-level="2.9.3" data-path="introR.html"><a href="introR.html#vectorsubset"><i class="fa fa-check"></i><b>2.9.3</b> Getting information out of vectors</a></li>
<li class="chapter" data-level="2.9.4" data-path="introR.html"><a href="introR.html#altering-the-elements-of-a-vector"><i class="fa fa-check"></i><b>2.9.4</b> Altering the elements of a vector</a></li>
<li class="chapter" data-level="2.9.5" data-path="introR.html"><a href="introR.html#veclength"><i class="fa fa-check"></i><b>2.9.5</b> Useful things to know about vectors</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="introR.html"><a href="introR.html#text"><i class="fa fa-check"></i><b>2.10</b> Storing text data</a>
<ul>
<li class="chapter" data-level="2.10.1" data-path="introR.html"><a href="introR.html#simpletext"><i class="fa fa-check"></i><b>2.10.1</b> Working with text</a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="introR.html"><a href="introR.html#logicals"><i class="fa fa-check"></i><b>2.11</b> Storing “true or false” data</a>
<ul>
<li class="chapter" data-level="2.11.1" data-path="introR.html"><a href="introR.html#assessing-mathematical-truths"><i class="fa fa-check"></i><b>2.11.1</b> Assessing mathematical truths</a></li>
<li class="chapter" data-level="2.11.2" data-path="introR.html"><a href="introR.html#logical-operations"><i class="fa fa-check"></i><b>2.11.2</b> Logical operations</a></li>
<li class="chapter" data-level="2.11.3" data-path="introR.html"><a href="introR.html#storing-and-using-logical-data"><i class="fa fa-check"></i><b>2.11.3</b> Storing and using logical data</a></li>
<li class="chapter" data-level="2.11.4" data-path="introR.html"><a href="introR.html#vectors-of-logicals"><i class="fa fa-check"></i><b>2.11.4</b> Vectors of logicals</a></li>
<li class="chapter" data-level="2.11.5" data-path="introR.html"><a href="introR.html#logictext"><i class="fa fa-check"></i><b>2.11.5</b> Applying logical operation to text</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="introR.html"><a href="introR.html#indexing"><i class="fa fa-check"></i><b>2.12</b> Indexing vectors</a>
<ul>
<li class="chapter" data-level="2.12.1" data-path="introR.html"><a href="introR.html#extracting-multiple-elements"><i class="fa fa-check"></i><b>2.12.1</b> Extracting multiple elements</a></li>
<li class="chapter" data-level="2.12.2" data-path="introR.html"><a href="introR.html#logical-indexing"><i class="fa fa-check"></i><b>2.12.2</b> Logical indexing</a></li>
</ul></li>
<li class="chapter" data-level="2.13" data-path="introR.html"><a href="introR.html#quitting-r"><i class="fa fa-check"></i><b>2.13</b> Quitting R</a></li>
<li class="chapter" data-level="2.14" data-path="introR.html"><a href="introR.html#summary"><i class="fa fa-check"></i><b>2.14</b> Summary</a></li>
<li class="chapter" data-level="2.15" data-path="introR.html"><a href="introR.html#mechanics"><i class="fa fa-check"></i><b>2.15</b> Additional R concepts</a></li>
<li class="chapter" data-level="2.16" data-path="introR.html"><a href="introR.html#comments"><i class="fa fa-check"></i><b>2.16</b> Using comments</a></li>
<li class="chapter" data-level="2.17" data-path="introR.html"><a href="introR.html#packageinstall"><i class="fa fa-check"></i><b>2.17</b> Installing and loading packages</a>
<ul>
<li class="chapter" data-level="2.17.1" data-path="introR.html"><a href="introR.html#the-package-panel-in-rstudio"><i class="fa fa-check"></i><b>2.17.1</b> The package panel in RStudio</a></li>
<li class="chapter" data-level="2.17.2" data-path="introR.html"><a href="introR.html#packageload"><i class="fa fa-check"></i><b>2.17.2</b> Loading a package</a></li>
<li class="chapter" data-level="2.17.3" data-path="introR.html"><a href="introR.html#packageunload"><i class="fa fa-check"></i><b>2.17.3</b> Unloading a package</a></li>
<li class="chapter" data-level="2.17.4" data-path="introR.html"><a href="introR.html#a-few-extra-comments"><i class="fa fa-check"></i><b>2.17.4</b> A few extra comments</a></li>
<li class="chapter" data-level="2.17.5" data-path="introR.html"><a href="introR.html#downloading-new-packages"><i class="fa fa-check"></i><b>2.17.5</b> Downloading new packages</a></li>
<li class="chapter" data-level="2.17.6" data-path="introR.html"><a href="introR.html#updating-r-and-r-packages"><i class="fa fa-check"></i><b>2.17.6</b> Updating R and R packages</a></li>
<li class="chapter" data-level="2.17.7" data-path="introR.html"><a href="introR.html#what-packages-does-this-book-use"><i class="fa fa-check"></i><b>2.17.7</b> What packages does this book use?</a></li>
</ul></li>
<li class="chapter" data-level="2.18" data-path="introR.html"><a href="introR.html#workspace"><i class="fa fa-check"></i><b>2.18</b> Managing the workspace</a>
<ul>
<li class="chapter" data-level="2.18.1" data-path="introR.html"><a href="introR.html#listing-the-contents-of-the-workspace"><i class="fa fa-check"></i><b>2.18.1</b> Listing the contents of the workspace</a></li>
<li class="chapter" data-level="2.18.2" data-path="introR.html"><a href="introR.html#removing-variables-from-the-workspace"><i class="fa fa-check"></i><b>2.18.2</b> Removing variables from the workspace</a></li>
</ul></li>
<li class="chapter" data-level="2.19" data-path="introR.html"><a href="introR.html#navigation"><i class="fa fa-check"></i><b>2.19</b> Navigating the file system</a>
<ul>
<li class="chapter" data-level="2.19.1" data-path="introR.html"><a href="introR.html#filesystem"><i class="fa fa-check"></i><b>2.19.1</b> The file system itself</a></li>
<li class="chapter" data-level="2.19.2" data-path="introR.html"><a href="introR.html#navigationR"><i class="fa fa-check"></i><b>2.19.2</b> Navigating the file system using the R console</a></li>
<li class="chapter" data-level="2.19.3" data-path="introR.html"><a href="introR.html#why-do-the-windows-paths-use-the-wrong-slash"><i class="fa fa-check"></i><b>2.19.3</b> Why do the Windows paths use the wrong slash?</a></li>
<li class="chapter" data-level="2.19.4" data-path="introR.html"><a href="introR.html#nav3"><i class="fa fa-check"></i><b>2.19.4</b> Navigating the file system using the RStudio file panel</a></li>
</ul></li>
<li class="chapter" data-level="2.20" data-path="introR.html"><a href="introR.html#load"><i class="fa fa-check"></i><b>2.20</b> Loading and saving data</a>
<ul>
<li class="chapter" data-level="2.20.1" data-path="introR.html"><a href="introR.html#loading-workspace-files-using-r"><i class="fa fa-check"></i><b>2.20.1</b> Loading workspace files using R</a></li>
<li class="chapter" data-level="2.20.2" data-path="introR.html"><a href="introR.html#loading-workspace-files-using-rstudio"><i class="fa fa-check"></i><b>2.20.2</b> Loading workspace files using RStudio</a></li>
<li class="chapter" data-level="2.20.3" data-path="introR.html"><a href="introR.html#loadingcsv"><i class="fa fa-check"></i><b>2.20.3</b> Importing data from CSV files using loadingcsv</a></li>
<li class="chapter" data-level="2.20.4" data-path="introR.html"><a href="introR.html#importing-data-from-csv-files-using-rstudio"><i class="fa fa-check"></i><b>2.20.4</b> Importing data from CSV files using RStudio</a></li>
<li class="chapter" data-level="2.20.5" data-path="introR.html"><a href="introR.html#saving-a-workspace-file-using-save"><i class="fa fa-check"></i><b>2.20.5</b> Saving a workspace file using <code>save</code></a></li>
<li class="chapter" data-level="2.20.6" data-path="introR.html"><a href="introR.html#save1"><i class="fa fa-check"></i><b>2.20.6</b> Saving a workspace file using RStudio</a></li>
<li class="chapter" data-level="2.20.7" data-path="introR.html"><a href="introR.html#other-things-you-might-want-to-save"><i class="fa fa-check"></i><b>2.20.7</b> Other things you might want to save</a></li>
</ul></li>
<li class="chapter" data-level="2.21" data-path="introR.html"><a href="introR.html#useful"><i class="fa fa-check"></i><b>2.21</b> Useful things to know about variables</a>
<ul>
<li class="chapter" data-level="2.21.1" data-path="introR.html"><a href="introR.html#specials"><i class="fa fa-check"></i><b>2.21.1</b> Special values</a></li>
<li class="chapter" data-level="2.21.2" data-path="introR.html"><a href="introR.html#names"><i class="fa fa-check"></i><b>2.21.2</b> Assigning names to vector elements</a></li>
<li class="chapter" data-level="2.21.3" data-path="introR.html"><a href="introR.html#variable-classes"><i class="fa fa-check"></i><b>2.21.3</b> Variable classes</a></li>
</ul></li>
<li class="chapter" data-level="2.22" data-path="introR.html"><a href="introR.html#factors"><i class="fa fa-check"></i><b>2.22</b> Factors</a>
<ul>
<li class="chapter" data-level="2.22.1" data-path="introR.html"><a href="introR.html#introducing-factors"><i class="fa fa-check"></i><b>2.22.1</b> Introducing factors</a></li>
<li class="chapter" data-level="2.22.2" data-path="introR.html"><a href="introR.html#labelling-the-factor-levels"><i class="fa fa-check"></i><b>2.22.2</b> Labelling the factor levels</a></li>
<li class="chapter" data-level="2.22.3" data-path="introR.html"><a href="introR.html#moving-on"><i class="fa fa-check"></i><b>2.22.3</b> Moving on…</a></li>
</ul></li>
<li class="chapter" data-level="2.23" data-path="introR.html"><a href="introR.html#dataframes"><i class="fa fa-check"></i><b>2.23</b> Data frames</a>
<ul>
<li class="chapter" data-level="2.23.1" data-path="introR.html"><a href="introR.html#introducing-data-frames"><i class="fa fa-check"></i><b>2.23.1</b> Introducing data frames</a></li>
<li class="chapter" data-level="2.23.2" data-path="introR.html"><a href="introR.html#pulling-out-the-contents-of-the-data-frame-using"><i class="fa fa-check"></i><b>2.23.2</b> Pulling out the contents of the data frame using <code>$</code></a></li>
<li class="chapter" data-level="2.23.3" data-path="introR.html"><a href="introR.html#getting-information-about-a-data-frame"><i class="fa fa-check"></i><b>2.23.3</b> Getting information about a data frame</a></li>
<li class="chapter" data-level="2.23.4" data-path="introR.html"><a href="introR.html#looking-for-more-on-data-frames"><i class="fa fa-check"></i><b>2.23.4</b> Looking for more on data frames?</a></li>
</ul></li>
<li class="chapter" data-level="2.24" data-path="introR.html"><a href="introR.html#lists"><i class="fa fa-check"></i><b>2.24</b> Lists</a></li>
<li class="chapter" data-level="2.25" data-path="introR.html"><a href="introR.html#formulas"><i class="fa fa-check"></i><b>2.25</b> Formulas</a></li>
<li class="chapter" data-level="2.26" data-path="introR.html"><a href="introR.html#generics"><i class="fa fa-check"></i><b>2.26</b> Generic functions</a></li>
<li class="chapter" data-level="2.27" data-path="introR.html"><a href="introR.html#help"><i class="fa fa-check"></i><b>2.27</b> Getting help</a>
<ul>
<li class="chapter" data-level="2.27.1" data-path="introR.html"><a href="introR.html#how-to-read-the-help-documentation"><i class="fa fa-check"></i><b>2.27.1</b> How to read the help documentation</a></li>
<li class="chapter" data-level="2.27.2" data-path="introR.html"><a href="introR.html#other-resources"><i class="fa fa-check"></i><b>2.27.2</b> Other resources</a></li>
</ul></li>
<li class="chapter" data-level="2.28" data-path="introR.html"><a href="introR.html#summary-1"><i class="fa fa-check"></i><b>2.28</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="descriptives.html"><a href="descriptives.html"><i class="fa fa-check"></i><b>3</b> Descriptive statistics</a>
<ul>
<li class="chapter" data-level="3.1" data-path="descriptives.html"><a href="descriptives.html#videos-1"><i class="fa fa-check"></i><b>3.1</b> Videos</a></li>
<li class="chapter" data-level="3.2" data-path="descriptives.html"><a href="descriptives.html#introduction-2"><i class="fa fa-check"></i><b>3.2</b> Introduction</a></li>
<li class="chapter" data-level="3.3" data-path="descriptives.html"><a href="descriptives.html#centraltendency"><i class="fa fa-check"></i><b>3.3</b> Measures of central tendency</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="descriptives.html"><a href="descriptives.html#mean"><i class="fa fa-check"></i><b>3.3.1</b> The mean</a></li>
<li class="chapter" data-level="3.3.2" data-path="descriptives.html"><a href="descriptives.html#calculating-the-mean-in-r"><i class="fa fa-check"></i><b>3.3.2</b> Calculating the mean in R</a></li>
<li class="chapter" data-level="3.3.3" data-path="descriptives.html"><a href="descriptives.html#median"><i class="fa fa-check"></i><b>3.3.3</b> The median</a></li>
<li class="chapter" data-level="3.3.4" data-path="descriptives.html"><a href="descriptives.html#mean-or-median-whats-the-difference"><i class="fa fa-check"></i><b>3.3.4</b> Mean or median? What’s the difference?</a></li>
<li class="chapter" data-level="3.3.5" data-path="descriptives.html"><a href="descriptives.html#housingpriceexample"><i class="fa fa-check"></i><b>3.3.5</b> A real life example</a></li>
<li class="chapter" data-level="3.3.6" data-path="descriptives.html"><a href="descriptives.html#trimmedmean"><i class="fa fa-check"></i><b>3.3.6</b> Trimmed mean</a></li>
<li class="chapter" data-level="3.3.7" data-path="descriptives.html"><a href="descriptives.html#mode"><i class="fa fa-check"></i><b>3.3.7</b> Mode</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="descriptives.html"><a href="descriptives.html#var"><i class="fa fa-check"></i><b>3.4</b> Measures of variability</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="descriptives.html"><a href="descriptives.html#range"><i class="fa fa-check"></i><b>3.4.1</b> Range</a></li>
<li class="chapter" data-level="3.4.2" data-path="descriptives.html"><a href="descriptives.html#interquartile-range"><i class="fa fa-check"></i><b>3.4.2</b> Interquartile range</a></li>
<li class="chapter" data-level="3.4.3" data-path="descriptives.html"><a href="descriptives.html#aad"><i class="fa fa-check"></i><b>3.4.3</b> Mean absolute deviation</a></li>
<li class="chapter" data-level="3.4.4" data-path="descriptives.html"><a href="descriptives.html#variance"><i class="fa fa-check"></i><b>3.4.4</b> Variance</a></li>
<li class="chapter" data-level="3.4.5" data-path="descriptives.html"><a href="descriptives.html#sd"><i class="fa fa-check"></i><b>3.4.5</b> Standard deviation</a></li>
<li class="chapter" data-level="3.4.6" data-path="descriptives.html"><a href="descriptives.html#mad"><i class="fa fa-check"></i><b>3.4.6</b> Median absolute deviation</a></li>
<li class="chapter" data-level="3.4.7" data-path="descriptives.html"><a href="descriptives.html#which-measure-to-use"><i class="fa fa-check"></i><b>3.4.7</b> Which measure to use?</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="descriptives.html"><a href="descriptives.html#skewandkurtosis"><i class="fa fa-check"></i><b>3.5</b> Skew and kurtosis</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="descriptives.html"><a href="descriptives.html#more-detail-on-skewness-measures"><i class="fa fa-check"></i><b>3.5.1</b> More detail on skewness measures</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="descriptives.html"><a href="descriptives.html#descriptive-summary"><i class="fa fa-check"></i><b>3.6</b> Getting an overall summary of a variable</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="descriptives.html"><a href="descriptives.html#summarising-a-variable"><i class="fa fa-check"></i><b>3.6.1</b> “Summarising” a variable</a></li>
<li class="chapter" data-level="3.6.2" data-path="descriptives.html"><a href="descriptives.html#summarising-a-data-frame"><i class="fa fa-check"></i><b>3.6.2</b> “Summarising” a data frame</a></li>
<li class="chapter" data-level="3.6.3" data-path="descriptives.html"><a href="descriptives.html#describing-a-data-frame"><i class="fa fa-check"></i><b>3.6.3</b> “Describing” a data frame</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="descriptives.html"><a href="descriptives.html#groupdescriptives"><i class="fa fa-check"></i><b>3.7</b> Descriptive statistics separately for each group</a></li>
<li class="chapter" data-level="3.8" data-path="descriptives.html"><a href="descriptives.html#good-descriptive-statistics-are-descriptive"><i class="fa fa-check"></i><b>3.8</b> Good descriptive statistics are descriptive!</a></li>
<li class="chapter" data-level="3.9" data-path="descriptives.html"><a href="descriptives.html#graphics"><i class="fa fa-check"></i><b>3.9</b> Drawing graphs</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="descriptives.html"><a href="descriptives.html#introplotting"><i class="fa fa-check"></i><b>3.9.1</b> An introduction to plotting</a></li>
<li class="chapter" data-level="3.9.2" data-path="descriptives.html"><a href="descriptives.html#hist"><i class="fa fa-check"></i><b>3.9.2</b> Histograms</a></li>
<li class="chapter" data-level="3.9.3" data-path="descriptives.html"><a href="descriptives.html#boxplots"><i class="fa fa-check"></i><b>3.9.3</b> Boxplots</a></li>
<li class="chapter" data-level="3.9.4" data-path="descriptives.html"><a href="descriptives.html#bargraph"><i class="fa fa-check"></i><b>3.9.4</b> Bar graphs</a></li>
<li class="chapter" data-level="3.9.5" data-path="descriptives.html"><a href="descriptives.html#saveimage"><i class="fa fa-check"></i><b>3.9.5</b> Saving image files using R and Rstudio</a></li>
<li class="chapter" data-level="3.9.6" data-path="descriptives.html"><a href="descriptives.html#summary-2"><i class="fa fa-check"></i><b>3.9.6</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html"><i class="fa fa-check"></i><b>4</b> Inferential statistics: The Central Limit Theorem</a>
<ul>
<li class="chapter" data-level="4.1" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#videos-2"><i class="fa fa-check"></i><b>4.1</b> Videos</a></li>
<li class="chapter" data-level="4.2" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#estimation"><i class="fa fa-check"></i><b>4.2</b> Introduction</a></li>
<li class="chapter" data-level="4.3" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#probstats"><i class="fa fa-check"></i><b>4.3</b> How are probability and statistics different?</a></li>
<li class="chapter" data-level="4.4" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#probmeaning"><i class="fa fa-check"></i><b>4.4</b> What does probability mean?</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#the-frequentist-view"><i class="fa fa-check"></i><b>4.4.1</b> The frequentist view</a></li>
<li class="chapter" data-level="4.4.2" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#the-bayesian-view"><i class="fa fa-check"></i><b>4.4.2</b> The Bayesian view</a></li>
<li class="chapter" data-level="4.4.3" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#whats-the-difference-and-who-is-right"><i class="fa fa-check"></i><b>4.4.3</b> What’s the difference? And who is right?</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#srs"><i class="fa fa-check"></i><b>4.5</b> Samples, populations and sampling</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#pop"><i class="fa fa-check"></i><b>4.5.1</b> Defining a population</a></li>
<li class="chapter" data-level="4.5.2" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#simple-random-samples"><i class="fa fa-check"></i><b>4.5.2</b> Simple random samples</a></li>
<li class="chapter" data-level="4.5.3" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#most-samples-are-not-simple-random-samples"><i class="fa fa-check"></i><b>4.5.3</b> Most samples are not simple random samples</a></li>
<li class="chapter" data-level="4.5.4" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#how-much-does-it-matter-if-you-dont-have-a-simple-random-sample"><i class="fa fa-check"></i><b>4.5.4</b> How much does it matter if you don’t have a simple random sample?</a></li>
<li class="chapter" data-level="4.5.5" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#population-parameters-and-sample-statistics"><i class="fa fa-check"></i><b>4.5.5</b> Population parameters and sample statistics</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#lawlargenumbers"><i class="fa fa-check"></i><b>4.6</b> The law of large numbers</a></li>
<li class="chapter" data-level="4.7" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#samplesandclt"><i class="fa fa-check"></i><b>4.7</b> Sampling distributions and the central limit theorem</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#samplingdists"><i class="fa fa-check"></i><b>4.7.1</b> Sampling distribution of the mean</a></li>
<li class="chapter" data-level="4.7.2" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#sample-size-and-population-size"><i class="fa fa-check"></i><b>4.7.2</b> Sample size and population size</a></li>
<li class="chapter" data-level="4.7.3" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#sampling-error"><i class="fa fa-check"></i><b>4.7.3</b> Sampling error</a></li>
<li class="chapter" data-level="4.7.4" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#another-sampling-distribution"><i class="fa fa-check"></i><b>4.7.4</b> Another sampling distribution</a></li>
<li class="chapter" data-level="4.7.5" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#defining-the-central-limit-theorem"><i class="fa fa-check"></i><b>4.7.5</b> Defining the central limit theorem</a></li>
<li class="chapter" data-level="4.7.6" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#more-on-standard-error"><i class="fa fa-check"></i><b>4.7.6</b> More on standard error</a></li>
<li class="chapter" data-level="4.7.7" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#the-sampling-distribution-tells-us-about-the-probability-of-sample-means"><i class="fa fa-check"></i><b>4.7.7</b> The sampling distribution tells us about the probability of sample means</a></li>
<li class="chapter" data-level="4.7.8" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#sampling-distributions-exist-for-any-sample-statistic"><i class="fa fa-check"></i><b>4.7.8</b> Sampling distributions exist for any sample statistic!</a></li>
<li class="chapter" data-level="4.7.9" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#clt"><i class="fa fa-check"></i><b>4.7.9</b> The central limit theorem</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#pointestimates"><i class="fa fa-check"></i><b>4.8</b> Estimating population parameters</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#estimating-the-population-mean"><i class="fa fa-check"></i><b>4.8.1</b> Estimating the population mean</a></li>
<li class="chapter" data-level="4.8.2" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#estimating-the-population-standard-deviation"><i class="fa fa-check"></i><b>4.8.2</b> Estimating the population standard deviation</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#ci"><i class="fa fa-check"></i><b>4.9</b> Estimating a confidence interval</a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#a-slight-mistake-in-the-formula"><i class="fa fa-check"></i><b>4.9.1</b> A slight mistake in the formula</a></li>
<li class="chapter" data-level="4.9.2" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#interpreting-a-confidence-interval"><i class="fa fa-check"></i><b>4.9.2</b> Interpreting a confidence interval</a></li>
<li class="chapter" data-level="4.9.3" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#calculating-confidence-intervals-in-r"><i class="fa fa-check"></i><b>4.9.3</b> Calculating confidence intervals in R</a></li>
<li class="chapter" data-level="4.9.4" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#ciplots"><i class="fa fa-check"></i><b>4.9.4</b> Plotting confidence intervals in R</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="inferential-statistics-the-central-limit-theorem.html"><a href="inferential-statistics-the-central-limit-theorem.html#summary-3"><i class="fa fa-check"></i><b>4.10</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="hypothesistesting.html"><a href="hypothesistesting.html"><i class="fa fa-check"></i><b>5</b> Hypothesis testing</a>
<ul>
<li class="chapter" data-level="5.1" data-path="hypothesistesting.html"><a href="hypothesistesting.html#videos-3"><i class="fa fa-check"></i><b>5.1</b> Videos</a></li>
<li class="chapter" data-level="5.2" data-path="hypothesistesting.html"><a href="hypothesistesting.html#introduction-3"><i class="fa fa-check"></i><b>5.2</b> Introduction</a></li>
<li class="chapter" data-level="5.3" data-path="hypothesistesting.html"><a href="hypothesistesting.html#hypotheses"><i class="fa fa-check"></i><b>5.3</b> A menagerie of hypotheses</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="hypothesistesting.html"><a href="hypothesistesting.html#research-hypotheses-versus-statistical-hypotheses"><i class="fa fa-check"></i><b>5.3.1</b> Research hypotheses versus statistical hypotheses</a></li>
<li class="chapter" data-level="5.3.2" data-path="hypothesistesting.html"><a href="hypothesistesting.html#null-hypotheses-and-alternative-hypotheses"><i class="fa fa-check"></i><b>5.3.2</b> Null hypotheses and alternative hypotheses</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="hypothesistesting.html"><a href="hypothesistesting.html#errortypes"><i class="fa fa-check"></i><b>5.4</b> Two types of errors</a></li>
<li class="chapter" data-level="5.5" data-path="hypothesistesting.html"><a href="hypothesistesting.html#teststatistics"><i class="fa fa-check"></i><b>5.5</b> Test statistics and sampling distributions</a></li>
<li class="chapter" data-level="5.6" data-path="hypothesistesting.html"><a href="hypothesistesting.html#decisionmaking"><i class="fa fa-check"></i><b>5.6</b> Making decisions</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="hypothesistesting.html"><a href="hypothesistesting.html#critical-regions-and-critical-values"><i class="fa fa-check"></i><b>5.6.1</b> Critical regions and critical values</a></li>
<li class="chapter" data-level="5.6.2" data-path="hypothesistesting.html"><a href="hypothesistesting.html#a-note-on-statistical-significance"><i class="fa fa-check"></i><b>5.6.2</b> A note on statistical “significance”</a></li>
<li class="chapter" data-level="5.6.3" data-path="hypothesistesting.html"><a href="hypothesistesting.html#onesidedtests"><i class="fa fa-check"></i><b>5.6.3</b> The difference between one sided and two sided tests</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="hypothesistesting.html"><a href="hypothesistesting.html#pvalue"><i class="fa fa-check"></i><b>5.7</b> The <span class="math inline">\(p\)</span> value of a test</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="hypothesistesting.html"><a href="hypothesistesting.html#a-softer-view-of-decision-making"><i class="fa fa-check"></i><b>5.7.1</b> A softer view of decision making</a></li>
<li class="chapter" data-level="5.7.2" data-path="hypothesistesting.html"><a href="hypothesistesting.html#the-probability-of-extreme-data"><i class="fa fa-check"></i><b>5.7.2</b> The probability of extreme data</a></li>
<li class="chapter" data-level="5.7.3" data-path="hypothesistesting.html"><a href="hypothesistesting.html#a-common-mistake"><i class="fa fa-check"></i><b>5.7.3</b> A common mistake</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="hypothesistesting.html"><a href="hypothesistesting.html#writeup"><i class="fa fa-check"></i><b>5.8</b> Reporting the results of a hypothesis test</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="hypothesistesting.html"><a href="hypothesistesting.html#the-issue"><i class="fa fa-check"></i><b>5.8.1</b> The issue</a></li>
<li class="chapter" data-level="5.8.2" data-path="hypothesistesting.html"><a href="hypothesistesting.html#two-proposed-solutions"><i class="fa fa-check"></i><b>5.8.2</b> Two proposed solutions</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="hypothesistesting.html"><a href="hypothesistesting.html#running-the-hypothesis-test-in-practice"><i class="fa fa-check"></i><b>5.9</b> Running the hypothesis test in practice</a></li>
<li class="chapter" data-level="5.10" data-path="hypothesistesting.html"><a href="hypothesistesting.html#effectsize"><i class="fa fa-check"></i><b>5.10</b> Effect size, sample size and power</a>
<ul>
<li class="chapter" data-level="5.10.1" data-path="hypothesistesting.html"><a href="hypothesistesting.html#the-power-function"><i class="fa fa-check"></i><b>5.10.1</b> The power function</a></li>
<li class="chapter" data-level="5.10.2" data-path="hypothesistesting.html"><a href="hypothesistesting.html#effect-size"><i class="fa fa-check"></i><b>5.10.2</b> Effect size</a></li>
<li class="chapter" data-level="5.10.3" data-path="hypothesistesting.html"><a href="hypothesistesting.html#increasing-the-power-of-your-study"><i class="fa fa-check"></i><b>5.10.3</b> Increasing the power of your study</a></li>
</ul></li>
<li class="chapter" data-level="5.11" data-path="hypothesistesting.html"><a href="hypothesistesting.html#nhstmess"><i class="fa fa-check"></i><b>5.11</b> Some issues to consider</a>
<ul>
<li class="chapter" data-level="5.11.1" data-path="hypothesistesting.html"><a href="hypothesistesting.html#neyman-versus-fisher"><i class="fa fa-check"></i><b>5.11.1</b> Neyman versus Fisher</a></li>
<li class="chapter" data-level="5.11.2" data-path="hypothesistesting.html"><a href="hypothesistesting.html#bayesians-versus-frequentists"><i class="fa fa-check"></i><b>5.11.2</b> Bayesians versus frequentists</a></li>
<li class="chapter" data-level="5.11.3" data-path="hypothesistesting.html"><a href="hypothesistesting.html#traps"><i class="fa fa-check"></i><b>5.11.3</b> Traps</a></li>
</ul></li>
<li class="chapter" data-level="5.12" data-path="hypothesistesting.html"><a href="hypothesistesting.html#summary-4"><i class="fa fa-check"></i><b>5.12</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="issues-in-hypothesis-testing.html"><a href="issues-in-hypothesis-testing.html"><i class="fa fa-check"></i><b>6</b> Issues in Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="6.1" data-path="issues-in-hypothesis-testing.html"><a href="issues-in-hypothesis-testing.html#videos-4"><i class="fa fa-check"></i><b>6.1</b> Videos</a></li>
<li class="chapter" data-level="6.2" data-path="issues-in-hypothesis-testing.html"><a href="issues-in-hypothesis-testing.html#introduction-4"><i class="fa fa-check"></i><b>6.2</b> Introduction</a></li>
<li class="chapter" data-level="6.3" data-path="issues-in-hypothesis-testing.html"><a href="issues-in-hypothesis-testing.html#the-researcher-affects-nhst-outcomes"><i class="fa fa-check"></i><b>6.3</b> The researcher affects NHST outcomes</a></li>
<li class="chapter" data-level="6.4" data-path="issues-in-hypothesis-testing.html"><a href="issues-in-hypothesis-testing.html#nhst-misunderstandings"><i class="fa fa-check"></i><b>6.4</b> NHST Misunderstandings</a></li>
<li class="chapter" data-level="6.5" data-path="issues-in-hypothesis-testing.html"><a href="issues-in-hypothesis-testing.html#nhst-issues"><i class="fa fa-check"></i><b>6.5</b> NHST Issues</a></li>
<li class="chapter" data-level="6.6" data-path="issues-in-hypothesis-testing.html"><a href="issues-in-hypothesis-testing.html#conclusions"><i class="fa fa-check"></i><b>6.6</b> Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="data-cleaning-and-missing-values-analysis.html"><a href="data-cleaning-and-missing-values-analysis.html"><i class="fa fa-check"></i><b>7</b> Data Cleaning and Missing Values Analysis</a>
<ul>
<li class="chapter" data-level="7.1" data-path="data-cleaning-and-missing-values-analysis.html"><a href="data-cleaning-and-missing-values-analysis.html#videos-5"><i class="fa fa-check"></i><b>7.1</b> Videos</a></li>
<li class="chapter" data-level="7.2" data-path="data-cleaning-and-missing-values-analysis.html"><a href="data-cleaning-and-missing-values-analysis.html#introduction-dealing-with-the-unexpected"><i class="fa fa-check"></i><b>7.2</b> Introduction: Dealing with the Unexpected</a></li>
<li class="chapter" data-level="7.3" data-path="data-cleaning-and-missing-values-analysis.html"><a href="data-cleaning-and-missing-values-analysis.html#data-cleaning"><i class="fa fa-check"></i><b>7.3</b> Data Cleaning</a></li>
<li class="chapter" data-level="7.4" data-path="data-cleaning-and-missing-values-analysis.html"><a href="data-cleaning-and-missing-values-analysis.html#a-general-plan-for-data-cleaning"><i class="fa fa-check"></i><b>7.4</b> A General Plan for Data Cleaning</a></li>
<li class="chapter" data-level="7.5" data-path="data-cleaning-and-missing-values-analysis.html"><a href="data-cleaning-and-missing-values-analysis.html#step-0.-design-your-research-to-mimimize-data-problems"><i class="fa fa-check"></i><b>7.5</b> Step 0. Design your Research to Mimimize Data Problems</a></li>
<li class="chapter" data-level="7.6" data-path="data-cleaning-and-missing-values-analysis.html"><a href="data-cleaning-and-missing-values-analysis.html#step-1.-examine-your-data"><i class="fa fa-check"></i><b>7.6</b> Step 1. Examine Your Data</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="data-cleaning-and-missing-values-analysis.html"><a href="data-cleaning-and-missing-values-analysis.html#sort"><i class="fa fa-check"></i><b>7.6.1</b> Sorting, flipping and merging data</a></li>
<li class="chapter" data-level="7.6.2" data-path="data-cleaning-and-missing-values-analysis.html"><a href="data-cleaning-and-missing-values-analysis.html#binding-vectors-together"><i class="fa fa-check"></i><b>7.6.2</b> Binding vectors together</a></li>
<li class="chapter" data-level="7.6.3" data-path="data-cleaning-and-missing-values-analysis.html"><a href="data-cleaning-and-missing-values-analysis.html#reshape"><i class="fa fa-check"></i><b>7.6.3</b> Reshaping a data frame</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="data-cleaning-and-missing-values-analysis.html"><a href="data-cleaning-and-missing-values-analysis.html#step-2.-outlier-analysis"><i class="fa fa-check"></i><b>7.7</b> Step 2. Outlier Analysis</a></li>
<li class="chapter" data-level="7.8" data-path="data-cleaning-and-missing-values-analysis.html"><a href="data-cleaning-and-missing-values-analysis.html#step-3.-missing-values-analysis"><i class="fa fa-check"></i><b>7.8</b> Step 3. Missing values analysis</a>
<ul>
<li class="chapter" data-level="7.8.1" data-path="introR.html"><a href="introR.html#specials"><i class="fa fa-check"></i><b>7.8.1</b> Special values in R</a></li>
<li class="chapter" data-level="7.8.2" data-path="data-cleaning-and-missing-values-analysis.html"><a href="data-cleaning-and-missing-values-analysis.html#missing"><i class="fa fa-check"></i><b>7.8.2</b> Handling missing values in R</a></li>
<li class="chapter" data-level="7.8.3" data-path="data-cleaning-and-missing-values-analysis.html"><a href="data-cleaning-and-missing-values-analysis.html#why-values-are-missing-mcar-mar-and-mnar"><i class="fa fa-check"></i><b>7.8.3</b> Why values are missing: MCAR, MAR, and MNAR</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="data-cleaning-and-missing-values-analysis.html"><a href="data-cleaning-and-missing-values-analysis.html#step-4.-test-specific-assumption-checking"><i class="fa fa-check"></i><b>7.9</b> Step 4. Test-specific assumption checking</a></li>
<li class="chapter" data-level="7.10" data-path="data-cleaning-and-missing-values-analysis.html"><a href="data-cleaning-and-missing-values-analysis.html#communicate-results-of-data-cleaning-in-apa-style"><i class="fa fa-check"></i><b>7.10</b> Communicate results of data cleaning in APA style</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>8</b> Regression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="regression.html"><a href="regression.html#videos-6"><i class="fa fa-check"></i><b>8.1</b> Videos</a></li>
<li class="chapter" data-level="8.2" data-path="regression.html"><a href="regression.html#introduction-5"><i class="fa fa-check"></i><b>8.2</b> Introduction</a></li>
<li class="chapter" data-level="8.3" data-path="regression.html"><a href="regression.html#the-general-linear-model-glm"><i class="fa fa-check"></i><b>8.3</b> The General Linear Model (GLM)</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="regression.html"><a href="regression.html#the-traditional-approach-two-kinds-of-parametric-statistical-tests"><i class="fa fa-check"></i><b>8.3.1</b> The Traditional approach: Two kinds of parametric statistical tests</a></li>
<li class="chapter" data-level="8.3.2" data-path="regression.html"><a href="regression.html#the-glm-approach"><i class="fa fa-check"></i><b>8.3.2</b> The GLM approach</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="regression.html"><a href="regression.html#correl"><i class="fa fa-check"></i><b>8.4</b> Correlations</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="regression.html"><a href="regression.html#the-data"><i class="fa fa-check"></i><b>8.4.1</b> The data</a></li>
<li class="chapter" data-level="8.4.2" data-path="regression.html"><a href="regression.html#the-strength-and-direction-of-a-relationship"><i class="fa fa-check"></i><b>8.4.2</b> The strength and direction of a relationship</a></li>
<li class="chapter" data-level="8.4.3" data-path="regression.html"><a href="regression.html#the-correlation-coefficient"><i class="fa fa-check"></i><b>8.4.3</b> The correlation coefficient</a></li>
<li class="chapter" data-level="8.4.4" data-path="regression.html"><a href="regression.html#calculating-correlations-in-r"><i class="fa fa-check"></i><b>8.4.4</b> Calculating correlations in R</a></li>
<li class="chapter" data-level="8.4.5" data-path="regression.html"><a href="regression.html#interpretingcorrelations"><i class="fa fa-check"></i><b>8.4.5</b> Interpreting a correlation</a></li>
<li class="chapter" data-level="8.4.6" data-path="regression.html"><a href="regression.html#spearmans-rank-correlations"><i class="fa fa-check"></i><b>8.4.6</b> Spearman’s rank correlations</a></li>
<li class="chapter" data-level="8.4.7" data-path="regression.html"><a href="regression.html#the-correlate-function"><i class="fa fa-check"></i><b>8.4.7</b> The <code>correlate()</code> function</a></li>
<li class="chapter" data-level="8.4.8" data-path="regression.html"><a href="regression.html#missing-values-in-pairwise-calculations-1"><i class="fa fa-check"></i><b>8.4.8</b> Missing values in pairwise calculations</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="regression.html"><a href="regression.html#introregression"><i class="fa fa-check"></i><b>8.5</b> Linear regression</a></li>
<li class="chapter" data-level="8.6" data-path="regression.html"><a href="regression.html#regressionestimation"><i class="fa fa-check"></i><b>8.6</b> Estimating a linear regression model</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="regression.html"><a href="regression.html#lm"><i class="fa fa-check"></i><b>8.6.1</b> Using the <code>lm()</code> function</a></li>
<li class="chapter" data-level="8.6.2" data-path="regression.html"><a href="regression.html#interpreting-the-estimated-model"><i class="fa fa-check"></i><b>8.6.2</b> Interpreting the estimated model</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="regression.html"><a href="regression.html#multipleregression"><i class="fa fa-check"></i><b>8.7</b> Multiple linear regression</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="regression.html"><a href="regression.html#doing-it-in-r"><i class="fa fa-check"></i><b>8.7.1</b> Doing it in R</a></li>
<li class="chapter" data-level="8.7.2" data-path="regression.html"><a href="regression.html#formula-for-the-general-case"><i class="fa fa-check"></i><b>8.7.2</b> Formula for the general case</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="regression.html"><a href="regression.html#r2"><i class="fa fa-check"></i><b>8.8</b> Quantifying the fit of the regression model</a>
<ul>
<li class="chapter" data-level="8.8.1" data-path="regression.html"><a href="regression.html#the-r2-value"><i class="fa fa-check"></i><b>8.8.1</b> The <span class="math inline">\(R^2\)</span> value</a></li>
<li class="chapter" data-level="8.8.2" data-path="regression.html"><a href="regression.html#the-relationship-between-regression-and-correlation"><i class="fa fa-check"></i><b>8.8.2</b> The relationship between regression and correlation</a></li>
<li class="chapter" data-level="8.8.3" data-path="regression.html"><a href="regression.html#the-adjusted-r2-value"><i class="fa fa-check"></i><b>8.8.3</b> The adjusted <span class="math inline">\(R^2\)</span> value</a></li>
</ul></li>
<li class="chapter" data-level="8.9" data-path="regression.html"><a href="regression.html#regressiontests"><i class="fa fa-check"></i><b>8.9</b> Hypothesis tests for regression models</a>
<ul>
<li class="chapter" data-level="8.9.1" data-path="regression.html"><a href="regression.html#testing-the-model-as-a-whole-the-omnibus-test"><i class="fa fa-check"></i><b>8.9.1</b> Testing the model as a whole: The omnibus test</a></li>
<li class="chapter" data-level="8.9.2" data-path="regression.html"><a href="regression.html#tests-for-individual-coefficients"><i class="fa fa-check"></i><b>8.9.2</b> Tests for individual coefficients</a></li>
<li class="chapter" data-level="8.9.3" data-path="regression.html"><a href="regression.html#regressionsummary"><i class="fa fa-check"></i><b>8.9.3</b> Running the hypothesis tests in R</a></li>
</ul></li>
<li class="chapter" data-level="8.10" data-path="regression.html"><a href="regression.html#corrhyp"><i class="fa fa-check"></i><b>8.10</b> Testing the significance of a correlation</a>
<ul>
<li class="chapter" data-level="8.10.1" data-path="regression.html"><a href="regression.html#hypothesis-tests-for-a-single-correlation"><i class="fa fa-check"></i><b>8.10.1</b> Hypothesis tests for a single correlation</a></li>
<li class="chapter" data-level="8.10.2" data-path="regression.html"><a href="regression.html#corrhyp2"><i class="fa fa-check"></i><b>8.10.2</b> Hypothesis tests for all pairwise correlations</a></li>
</ul></li>
<li class="chapter" data-level="8.11" data-path="regression.html"><a href="regression.html#regressioncoefs"><i class="fa fa-check"></i><b>8.11</b> Regarding regression coefficients</a>
<ul>
<li class="chapter" data-level="8.11.1" data-path="regression.html"><a href="regression.html#confidence-intervals-for-the-coefficients"><i class="fa fa-check"></i><b>8.11.1</b> Confidence intervals for the coefficients</a></li>
<li class="chapter" data-level="8.11.2" data-path="regression.html"><a href="regression.html#calculating-standardised-regression-coefficients"><i class="fa fa-check"></i><b>8.11.2</b> Calculating standardised regression coefficients</a></li>
</ul></li>
<li class="chapter" data-level="8.12" data-path="regression.html"><a href="regression.html#regressionassumptions"><i class="fa fa-check"></i><b>8.12</b> Assumptions of regression</a></li>
<li class="chapter" data-level="8.13" data-path="regression.html"><a href="regression.html#regressiondiagnostics"><i class="fa fa-check"></i><b>8.13</b> Model checking</a>
<ul>
<li class="chapter" data-level="8.13.1" data-path="regression.html"><a href="regression.html#three-kinds-of-residuals"><i class="fa fa-check"></i><b>8.13.1</b> Three kinds of residuals</a></li>
<li class="chapter" data-level="8.13.2" data-path="regression.html"><a href="regression.html#regressionoutliers"><i class="fa fa-check"></i><b>8.13.2</b> Three kinds of anomalous data</a></li>
<li class="chapter" data-level="8.13.3" data-path="regression.html"><a href="regression.html#regressionnormality"><i class="fa fa-check"></i><b>8.13.3</b> Checking the normality of the residuals</a></li>
<li class="chapter" data-level="8.13.4" data-path="regression.html"><a href="regression.html#regressionlinearity"><i class="fa fa-check"></i><b>8.13.4</b> Checking the linearity of the relationship</a></li>
<li class="chapter" data-level="8.13.5" data-path="regression.html"><a href="regression.html#regressionhomogeneity"><i class="fa fa-check"></i><b>8.13.5</b> Checking the homogeneity of variance</a></li>
<li class="chapter" data-level="8.13.6" data-path="regression.html"><a href="regression.html#regressioncollinearity"><i class="fa fa-check"></i><b>8.13.6</b> Checking for collinearity</a></li>
</ul></li>
<li class="chapter" data-level="8.14" data-path="regression.html"><a href="regression.html#modelselreg"><i class="fa fa-check"></i><b>8.14</b> Model selection</a>
<ul>
<li class="chapter" data-level="8.14.1" data-path="regression.html"><a href="regression.html#backward-elimination"><i class="fa fa-check"></i><b>8.14.1</b> Backward elimination</a></li>
<li class="chapter" data-level="8.14.2" data-path="regression.html"><a href="regression.html#forward-selection"><i class="fa fa-check"></i><b>8.14.2</b> Forward selection</a></li>
<li class="chapter" data-level="8.14.3" data-path="regression.html"><a href="regression.html#a-caveat"><i class="fa fa-check"></i><b>8.14.3</b> A caveat</a></li>
<li class="chapter" data-level="8.14.4" data-path="regression.html"><a href="regression.html#comparing-two-regression-models"><i class="fa fa-check"></i><b>8.14.4</b> Comparing two regression models</a></li>
</ul></li>
<li class="chapter" data-level="8.15" data-path="regression.html"><a href="regression.html#practical-issues-in-correlation-and-regression"><i class="fa fa-check"></i><b>8.15</b> Practical Issues in Correlation and Regression</a>
<ul>
<li class="chapter" data-level="8.15.1" data-path="regression.html"><a href="regression.html#correlation-is-not-causation"><i class="fa fa-check"></i><b>8.15.1</b> Correlation is not causation</a></li>
<li class="chapter" data-level="8.15.2" data-path="regression.html"><a href="regression.html#interpreting-nhst-in-big-data"><i class="fa fa-check"></i><b>8.15.2</b> Interpreting NHST in Big Data</a></li>
<li class="chapter" data-level="8.15.3" data-path="regression.html"><a href="regression.html#outliers"><i class="fa fa-check"></i><b>8.15.3</b> Outliers</a></li>
<li class="chapter" data-level="8.15.4" data-path="regression.html"><a href="regression.html#restriction-of-range"><i class="fa fa-check"></i><b>8.15.4</b> Restriction of Range</a></li>
<li class="chapter" data-level="8.15.5" data-path="regression.html"><a href="regression.html#regression-toward-the-mean"><i class="fa fa-check"></i><b>8.15.5</b> Regression Toward the Mean</a></li>
<li class="chapter" data-level="8.15.6" data-path="regression.html"><a href="regression.html#report-effect-size"><i class="fa fa-check"></i><b>8.15.6</b> Report Effect Size</a></li>
<li class="chapter" data-level="8.15.7" data-path="regression.html"><a href="regression.html#what-are-degrees-of-freedom-again"><i class="fa fa-check"></i><b>8.15.7</b> What are Degrees of Freedom, again?</a></li>
</ul></li>
<li class="chapter" data-level="8.16" data-path="regression.html"><a href="regression.html#summary-5"><i class="fa fa-check"></i><b>8.16</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ttest.html"><a href="ttest.html"><i class="fa fa-check"></i><b>9</b> T-Tests</a>
<ul>
<li class="chapter" data-level="9.1" data-path="ttest.html"><a href="ttest.html#videos-7"><i class="fa fa-check"></i><b>9.1</b> Videos</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="ttest.html"><a href="ttest.html#t-tests"><i class="fa fa-check"></i><b>9.1.1</b> T-Tests</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="ttest.html"><a href="ttest.html#groupcomparisonscompared"><i class="fa fa-check"></i><b>9.2</b> Comparison of tests that compare groups</a></li>
<li class="chapter" data-level="9.3" data-path="ttest.html"><a href="ttest.html#introduction-6"><i class="fa fa-check"></i><b>9.3</b> Introduction</a></li>
<li class="chapter" data-level="9.4" data-path="ttest.html"><a href="ttest.html#onesamplettest"><i class="fa fa-check"></i><b>9.4</b> The one-sample <span class="math inline">\(t\)</span>-test</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="ttest.html"><a href="ttest.html#introducing-the-t-test"><i class="fa fa-check"></i><b>9.4.1</b> Introducing the <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="9.4.2" data-path="ttest.html"><a href="ttest.html#doing-the-test-in-r"><i class="fa fa-check"></i><b>9.4.2</b> Doing the test in R</a></li>
<li class="chapter" data-level="9.4.3" data-path="ttest.html"><a href="ttest.html#ttestoneassumptions"><i class="fa fa-check"></i><b>9.4.3</b> Assumptions of the one sample <span class="math inline">\(t\)</span>-test</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="ttest.html"><a href="ttest.html#studentttest"><i class="fa fa-check"></i><b>9.5</b> The independent samples <span class="math inline">\(t\)</span>-test (Student test)</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="ttest.html"><a href="ttest.html#the-data-1"><i class="fa fa-check"></i><b>9.5.1</b> The data</a></li>
<li class="chapter" data-level="9.5.2" data-path="ttest.html"><a href="ttest.html#introducing-the-test"><i class="fa fa-check"></i><b>9.5.2</b> Introducing the test</a></li>
<li class="chapter" data-level="9.5.3" data-path="ttest.html"><a href="ttest.html#a-pooled-estimate-of-the-standard-deviation"><i class="fa fa-check"></i><b>9.5.3</b> A “pooled estimate” of the standard deviation</a></li>
<li class="chapter" data-level="9.5.4" data-path="ttest.html"><a href="ttest.html#the-same-pooled-estimate-described-differently"><i class="fa fa-check"></i><b>9.5.4</b> The same pooled estimate, described differently</a></li>
<li class="chapter" data-level="9.5.5" data-path="ttest.html"><a href="ttest.html#completing-the-test"><i class="fa fa-check"></i><b>9.5.5</b> Completing the test</a></li>
<li class="chapter" data-level="9.5.6" data-path="ttest.html"><a href="ttest.html#doing-the-test-in-r-1"><i class="fa fa-check"></i><b>9.5.6</b> Doing the test in R</a></li>
<li class="chapter" data-level="9.5.7" data-path="ttest.html"><a href="ttest.html#positive-and-negative-t-values"><i class="fa fa-check"></i><b>9.5.7</b> Positive and negative <span class="math inline">\(t\)</span> values</a></li>
<li class="chapter" data-level="9.5.8" data-path="ttest.html"><a href="ttest.html#studentassumptions"><i class="fa fa-check"></i><b>9.5.8</b> Assumptions of the test</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="ttest.html"><a href="ttest.html#welchttest"><i class="fa fa-check"></i><b>9.6</b> The independent samples <span class="math inline">\(t\)</span>-test (Welch test)</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="ttest.html"><a href="ttest.html#doing-the-test-in-r-2"><i class="fa fa-check"></i><b>9.6.1</b> Doing the test in R</a></li>
<li class="chapter" data-level="9.6.2" data-path="ttest.html"><a href="ttest.html#assumptions-of-the-test"><i class="fa fa-check"></i><b>9.6.2</b> Assumptions of the test</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="ttest.html"><a href="ttest.html#pairedsamplesttest"><i class="fa fa-check"></i><b>9.7</b> The paired-samples <span class="math inline">\(t\)</span>-test</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="ttest.html"><a href="ttest.html#the-data-2"><i class="fa fa-check"></i><b>9.7.1</b> The data</a></li>
<li class="chapter" data-level="9.7.2" data-path="ttest.html"><a href="ttest.html#what-is-the-paired-samples-t-test"><i class="fa fa-check"></i><b>9.7.2</b> What is the paired samples <span class="math inline">\(t\)</span>-test?</a></li>
<li class="chapter" data-level="9.7.3" data-path="ttest.html"><a href="ttest.html#doing-the-test-in-r-part-1"><i class="fa fa-check"></i><b>9.7.3</b> Doing the test in R, part 1</a></li>
<li class="chapter" data-level="9.7.4" data-path="ttest.html"><a href="ttest.html#doing-the-test-in-r-part-2"><i class="fa fa-check"></i><b>9.7.4</b> Doing the test in R, part 2</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="ttest.html"><a href="ttest.html#one-sided-tests"><i class="fa fa-check"></i><b>9.8</b> One sided tests</a></li>
<li class="chapter" data-level="9.9" data-path="ttest.html"><a href="ttest.html#ttestfunction"><i class="fa fa-check"></i><b>9.9</b> Using the t.test() function</a></li>
<li class="chapter" data-level="9.10" data-path="ttest.html"><a href="ttest.html#cohensd"><i class="fa fa-check"></i><b>9.10</b> Effect size</a>
<ul>
<li class="chapter" data-level="9.10.1" data-path="ttest.html"><a href="ttest.html#cohens-d-from-one-sample"><i class="fa fa-check"></i><b>9.10.1</b> Cohen’s <span class="math inline">\(d\)</span> from one sample</a></li>
<li class="chapter" data-level="9.10.2" data-path="ttest.html"><a href="ttest.html#cohens-d-from-a-student-t-test"><i class="fa fa-check"></i><b>9.10.2</b> Cohen’s <span class="math inline">\(d\)</span> from a Student <span class="math inline">\(t\)</span> test</a></li>
<li class="chapter" data-level="9.10.3" data-path="ttest.html"><a href="ttest.html#cohens-d-from-a-welch-test"><i class="fa fa-check"></i><b>9.10.3</b> Cohen’s <span class="math inline">\(d\)</span> from a Welch test</a></li>
<li class="chapter" data-level="9.10.4" data-path="ttest.html"><a href="ttest.html#cohens-d-from-a-paired-samples-test"><i class="fa fa-check"></i><b>9.10.4</b> Cohen’s <span class="math inline">\(d\)</span> from a paired-samples test</a></li>
</ul></li>
<li class="chapter" data-level="9.11" data-path="ttest.html"><a href="ttest.html#shapiro"><i class="fa fa-check"></i><b>9.11</b> Checking the normality of a sample</a>
<ul>
<li class="chapter" data-level="9.11.1" data-path="ttest.html"><a href="ttest.html#qq-plots"><i class="fa fa-check"></i><b>9.11.1</b> QQ plots</a></li>
<li class="chapter" data-level="9.11.2" data-path="ttest.html"><a href="ttest.html#shapiro-wilk-tests"><i class="fa fa-check"></i><b>9.11.2</b> Shapiro-Wilk tests</a></li>
</ul></li>
<li class="chapter" data-level="9.12" data-path="ttest.html"><a href="ttest.html#wilcox"><i class="fa fa-check"></i><b>9.12</b> Testing non-normal data with Wilcoxon tests</a>
<ul>
<li class="chapter" data-level="9.12.1" data-path="ttest.html"><a href="ttest.html#two-sample-wilcoxon-test"><i class="fa fa-check"></i><b>9.12.1</b> Two sample Wilcoxon test</a></li>
<li class="chapter" data-level="9.12.2" data-path="ttest.html"><a href="ttest.html#one-sample-wilcoxon-test"><i class="fa fa-check"></i><b>9.12.2</b> One sample Wilcoxon test</a></li>
</ul></li>
<li class="chapter" data-level="9.13" data-path="ttest.html"><a href="ttest.html#summary-6"><i class="fa fa-check"></i><b>9.13</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>10</b> One-way ANOVA</a>
<ul>
<li class="chapter" data-level="10.1" data-path="anova.html"><a href="anova.html#videos-8"><i class="fa fa-check"></i><b>10.1</b> Videos</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="anova.html"><a href="anova.html#one-way-between-subjects-anova"><i class="fa fa-check"></i><b>10.1.1</b> One-Way, Between-Subjects ANOVA</a></li>
<li class="chapter" data-level="10.1.2" data-path="anova.html"><a href="anova.html#repeated-measures-anova"><i class="fa fa-check"></i><b>10.1.2</b> Repeated Measures ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="anova.html"><a href="anova.html#anxifree"><i class="fa fa-check"></i><b>10.2</b> An illustrative data set</a></li>
<li class="chapter" data-level="10.3" data-path="anova.html"><a href="anova.html#anovaintro"><i class="fa fa-check"></i><b>10.3</b> How ANOVA works</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="anova.html"><a href="anova.html#two-formulas-for-the-variance-of-y"><i class="fa fa-check"></i><b>10.3.1</b> Two formulas for the variance of <span class="math inline">\(Y\)</span></a></li>
<li class="chapter" data-level="10.3.2" data-path="anova.html"><a href="anova.html#from-variances-to-sums-of-squares"><i class="fa fa-check"></i><b>10.3.2</b> From variances to sums of squares</a></li>
<li class="chapter" data-level="10.3.3" data-path="anova.html"><a href="anova.html#from-sums-of-squares-to-the-f-test"><i class="fa fa-check"></i><b>10.3.3</b> From sums of squares to the <span class="math inline">\(F\)</span>-test</a></li>
<li class="chapter" data-level="10.3.4" data-path="anova.html"><a href="anova.html#anovamodel"><i class="fa fa-check"></i><b>10.3.4</b> The model for the data and the meaning of <span class="math inline">\(F\)</span> (advanced)</a></li>
<li class="chapter" data-level="10.3.5" data-path="anova.html"><a href="anova.html#anovacalc"><i class="fa fa-check"></i><b>10.3.5</b> A worked example</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="anova.html"><a href="anova.html#introduceaov"><i class="fa fa-check"></i><b>10.4</b> Running an ANOVA in R</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="anova.html"><a href="anova.html#using-the-aov-function-to-specify-your-anova"><i class="fa fa-check"></i><b>10.4.1</b> Using the <code>aov()</code> function to specify your ANOVA</a></li>
<li class="chapter" data-level="10.4.2" data-path="anova.html"><a href="anova.html#aovobjects"><i class="fa fa-check"></i><b>10.4.2</b> Understanding what the <code>aov()</code> function produces</a></li>
<li class="chapter" data-level="10.4.3" data-path="anova.html"><a href="anova.html#running-the-hypothesis-tests-for-the-anova"><i class="fa fa-check"></i><b>10.4.3</b> Running the hypothesis tests for the ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="anova.html"><a href="anova.html#etasquared"><i class="fa fa-check"></i><b>10.5</b> Effect size</a></li>
<li class="chapter" data-level="10.6" data-path="anova.html"><a href="anova.html#anovaandt"><i class="fa fa-check"></i><b>10.6</b> On the relationship between ANOVA and the Student <span class="math inline">\(t\)</span> test</a></li>
<li class="chapter" data-level="10.7" data-path="anova.html"><a href="anova.html#summary-7"><i class="fa fa-check"></i><b>10.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html"><i class="fa fa-check"></i><b>11</b> Multiple comparisons</a>
<ul>
<li class="chapter" data-level="11.1" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#posthoc"><i class="fa fa-check"></i><b>11.1</b> Multiple comparisons and post hoc tests</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#running-pairwise-t-tests"><i class="fa fa-check"></i><b>11.1.1</b> Running “pairwise” <span class="math inline">\(t\)</span>-tests</a></li>
<li class="chapter" data-level="11.1.2" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#corrections-for-multiple-testing"><i class="fa fa-check"></i><b>11.1.2</b> Corrections for multiple testing</a></li>
<li class="chapter" data-level="11.1.3" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#bonferroni-corrections"><i class="fa fa-check"></i><b>11.1.3</b> Bonferroni corrections</a></li>
<li class="chapter" data-level="11.1.4" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#holm-corrections"><i class="fa fa-check"></i><b>11.1.4</b> Holm corrections</a></li>
<li class="chapter" data-level="11.1.5" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#writing-up-the-post-hoc-test"><i class="fa fa-check"></i><b>11.1.5</b> Writing up the post hoc test</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#anovaassumptions"><i class="fa fa-check"></i><b>11.2</b> Assumptions of one-way ANOVA</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#how-robust-is-anova"><i class="fa fa-check"></i><b>11.2.1</b> How robust is ANOVA?</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#levene"><i class="fa fa-check"></i><b>11.3</b> Checking the homogeneity of variance assumption</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#running-the-levenes-test-in-r"><i class="fa fa-check"></i><b>11.3.1</b> Running the Levene’s test in R</a></li>
<li class="chapter" data-level="11.3.2" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#additional-comments"><i class="fa fa-check"></i><b>11.3.2</b> Additional comments</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#welchoneway"><i class="fa fa-check"></i><b>11.4</b> Removing the homogeneity of variance assumption</a></li>
<li class="chapter" data-level="11.5" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#anovanormality"><i class="fa fa-check"></i><b>11.5</b> Checking the normality assumption</a></li>
<li class="chapter" data-level="11.6" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#kruskalwallis"><i class="fa fa-check"></i><b>11.6</b> Removing the normality assumption</a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#the-logic-behind-the-kruskal-wallis-test"><i class="fa fa-check"></i><b>11.6.1</b> The logic behind the Kruskal-Wallis test</a></li>
<li class="chapter" data-level="11.6.2" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#additional-details"><i class="fa fa-check"></i><b>11.6.2</b> Additional details</a></li>
<li class="chapter" data-level="11.6.3" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#how-to-run-the-kruskal-wallis-test-in-r"><i class="fa fa-check"></i><b>11.6.3</b> How to run the Kruskal-Wallis test in R</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#summary-8"><i class="fa fa-check"></i><b>11.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="statistics-reference.html"><a href="statistics-reference.html"><i class="fa fa-check"></i><b>12</b> Statistics Reference</a>
<ul>
<li class="chapter" data-level="12.1" data-path="statistics-reference.html"><a href="statistics-reference.html#one-sample-z-test"><i class="fa fa-check"></i><b>12.1</b> One-Sample <em>z</em>-Test</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="statistics-reference.html"><a href="statistics-reference.html#definition"><i class="fa fa-check"></i><b>12.1.1</b> Definition</a></li>
<li class="chapter" data-level="12.1.2" data-path="statistics-reference.html"><a href="statistics-reference.html#test-statistic"><i class="fa fa-check"></i><b>12.1.2</b> Test Statistic</a></li>
<li class="chapter" data-level="12.1.3" data-path="statistics-reference.html"><a href="statistics-reference.html#assumptions-required-data"><i class="fa fa-check"></i><b>12.1.3</b> Assumptions &amp; Required Data</a></li>
<li class="chapter" data-level="12.1.4" data-path="statistics-reference.html"><a href="statistics-reference.html#when-to-use-it"><i class="fa fa-check"></i><b>12.1.4</b> When to use it</a></li>
<li class="chapter" data-level="12.1.5" data-path="statistics-reference.html"><a href="statistics-reference.html#example"><i class="fa fa-check"></i><b>12.1.5</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="statistics-reference.html"><a href="statistics-reference.html#correlation"><i class="fa fa-check"></i><b>12.2</b> Correlation</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="statistics-reference.html"><a href="statistics-reference.html#definition-1"><i class="fa fa-check"></i><b>12.2.1</b> Definition</a></li>
<li class="chapter" data-level="12.2.2" data-path="statistics-reference.html"><a href="statistics-reference.html#test-statistic-1"><i class="fa fa-check"></i><b>12.2.2</b> Test Statistic</a></li>
<li class="chapter" data-level="12.2.3" data-path="statistics-reference.html"><a href="statistics-reference.html#assumptions-required-data-1"><i class="fa fa-check"></i><b>12.2.3</b> Assumptions &amp; Required Data</a></li>
<li class="chapter" data-level="12.2.4" data-path="statistics-reference.html"><a href="statistics-reference.html#when-to-use-it-1"><i class="fa fa-check"></i><b>12.2.4</b> When to use it</a></li>
<li class="chapter" data-level="12.2.5" data-path="statistics-reference.html"><a href="statistics-reference.html#example-1"><i class="fa fa-check"></i><b>12.2.5</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="statistics-reference.html"><a href="statistics-reference.html#linear-regression"><i class="fa fa-check"></i><b>12.3</b> Linear Regression</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="statistics-reference.html"><a href="statistics-reference.html#definition-2"><i class="fa fa-check"></i><b>12.3.1</b> Definition</a></li>
<li class="chapter" data-level="12.3.2" data-path="statistics-reference.html"><a href="statistics-reference.html#test-statistic-2"><i class="fa fa-check"></i><b>12.3.2</b> Test Statistic</a></li>
<li class="chapter" data-level="12.3.3" data-path="statistics-reference.html"><a href="statistics-reference.html#assumptions-required-data-2"><i class="fa fa-check"></i><b>12.3.3</b> Assumptions &amp; Required Data</a></li>
<li class="chapter" data-level="12.3.4" data-path="statistics-reference.html"><a href="statistics-reference.html#when-to-use-it-2"><i class="fa fa-check"></i><b>12.3.4</b> When to use it</a></li>
<li class="chapter" data-level="12.3.5" data-path="statistics-reference.html"><a href="statistics-reference.html#example-2"><i class="fa fa-check"></i><b>12.3.5</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="statistics-reference.html"><a href="statistics-reference.html#one-sample-t-test"><i class="fa fa-check"></i><b>12.4</b> One-Sample <em>t</em>-Test</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="statistics-reference.html"><a href="statistics-reference.html#definition-3"><i class="fa fa-check"></i><b>12.4.1</b> Definition</a></li>
<li class="chapter" data-level="12.4.2" data-path="statistics-reference.html"><a href="statistics-reference.html#test-statistic-3"><i class="fa fa-check"></i><b>12.4.2</b> Test Statistic</a></li>
<li class="chapter" data-level="12.4.3" data-path="statistics-reference.html"><a href="statistics-reference.html#assumptions-required-data-3"><i class="fa fa-check"></i><b>12.4.3</b> Assumptions &amp; Required Data</a></li>
<li class="chapter" data-level="12.4.4" data-path="statistics-reference.html"><a href="statistics-reference.html#when-to-use-it-3"><i class="fa fa-check"></i><b>12.4.4</b> When to use it</a></li>
<li class="chapter" data-level="12.4.5" data-path="statistics-reference.html"><a href="statistics-reference.html#example-3"><i class="fa fa-check"></i><b>12.4.5</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="statistics-reference.html"><a href="statistics-reference.html#paired-samples-t-test"><i class="fa fa-check"></i><b>12.5</b> Paired Samples T-Test</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="statistics-reference.html"><a href="statistics-reference.html#definition-4"><i class="fa fa-check"></i><b>12.5.1</b> Definition</a></li>
<li class="chapter" data-level="12.5.2" data-path="statistics-reference.html"><a href="statistics-reference.html#test-statistic-4"><i class="fa fa-check"></i><b>12.5.2</b> Test Statistic</a></li>
<li class="chapter" data-level="12.5.3" data-path="statistics-reference.html"><a href="statistics-reference.html#assumptions-required-data-4"><i class="fa fa-check"></i><b>12.5.3</b> Assumptions &amp; Required Data</a></li>
<li class="chapter" data-level="12.5.4" data-path="statistics-reference.html"><a href="statistics-reference.html#when-to-use-it-4"><i class="fa fa-check"></i><b>12.5.4</b> When to use it</a></li>
<li class="chapter" data-level="12.5.5" data-path="statistics-reference.html"><a href="statistics-reference.html#example-4"><i class="fa fa-check"></i><b>12.5.5</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="statistics-reference.html"><a href="statistics-reference.html#independent-samples-t-test"><i class="fa fa-check"></i><b>12.6</b> Independent Samples <span class="math inline">\(t\)</span>-Test</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="statistics-reference.html"><a href="statistics-reference.html#definition-5"><i class="fa fa-check"></i><b>12.6.1</b> Definition</a></li>
<li class="chapter" data-level="12.6.2" data-path="statistics-reference.html"><a href="statistics-reference.html#test-statistic-5"><i class="fa fa-check"></i><b>12.6.2</b> Test Statistic</a></li>
<li class="chapter" data-level="12.6.3" data-path="statistics-reference.html"><a href="statistics-reference.html#assumptions-required-data-5"><i class="fa fa-check"></i><b>12.6.3</b> Assumptions &amp; Required Data</a></li>
<li class="chapter" data-level="12.6.4" data-path="statistics-reference.html"><a href="statistics-reference.html#when-to-use-it-5"><i class="fa fa-check"></i><b>12.6.4</b> When to use it</a></li>
<li class="chapter" data-level="12.6.5" data-path="statistics-reference.html"><a href="statistics-reference.html#example-5"><i class="fa fa-check"></i><b>12.6.5</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="statistics-reference.html"><a href="statistics-reference.html#one-way-anova"><i class="fa fa-check"></i><b>12.7</b> One-Way ANOVA</a>
<ul>
<li class="chapter" data-level="12.7.1" data-path="statistics-reference.html"><a href="statistics-reference.html#definition-6"><i class="fa fa-check"></i><b>12.7.1</b> Definition</a></li>
<li class="chapter" data-level="12.7.2" data-path="statistics-reference.html"><a href="statistics-reference.html#test-statistic-6"><i class="fa fa-check"></i><b>12.7.2</b> Test Statistic</a></li>
<li class="chapter" data-level="12.7.3" data-path="statistics-reference.html"><a href="statistics-reference.html#assumptions-required-data-6"><i class="fa fa-check"></i><b>12.7.3</b> Assumptions &amp; Required Data</a></li>
<li class="chapter" data-level="12.7.4" data-path="statistics-reference.html"><a href="statistics-reference.html#when-to-use-it-6"><i class="fa fa-check"></i><b>12.7.4</b> When to use it</a></li>
<li class="chapter" data-level="12.7.5" data-path="statistics-reference.html"><a href="statistics-reference.html#example-between-subjects"><i class="fa fa-check"></i><b>12.7.5</b> Example: Between-Subjects</a></li>
<li class="chapter" data-level="12.7.6" data-path="statistics-reference.html"><a href="statistics-reference.html#example-within-subjects"><i class="fa fa-check"></i><b>12.7.6</b> Example: Within-Subjects</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Advanced Statistics Remix</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="anova" class="section level1" number="10">
<h1><span class="header-section-number">Chapter 10</span> One-way ANOVA</h1>
<div id="videos-8" class="section level2" number="10.1">
<h2><span class="header-section-number">10.1</span> Videos</h2>
<div id="one-way-between-subjects-anova" class="section level3" number="10.1.1">
<h3><span class="header-section-number">10.1.1</span> One-Way, Between-Subjects ANOVA</h3>
<p><a href="https://www.youtube.com/watch?v=okL4x7tFtPs">One-Way ANOVA Basics (only first 33 minutes, the rest is on SPSS)</a></p>
<p><a href="https://www.youtube.com/watch?v=krhErceFJnE">Between-subjects ANOVA and multiple comparisons in R - 11 minutes</a></p>
</div>
<div id="repeated-measures-anova" class="section level3" number="10.1.2">
<h3><span class="header-section-number">10.1.2</span> Repeated Measures ANOVA</h3>
<p><a href="https://www.youtube.com/watch?v=xJexuEEdIe0">Within-subjects ANOVA basics - 27 min.</a></p>
<p>This chapter introduces one of the most widely used tools in statistics, known as “the analysis of variance,” which is usually referred to as ANOVA. The basic technique was developed by Sir Ronald Fisher in the early 20th century, and it is to him that we owe the rather unfortunate terminology. The term ANOVA is a little misleading, in two respects. Firstly, although the name of the technique refers to variances, ANOVA is concerned with investigating differences in means. Secondly, there are several different things out there that are all referred to as ANOVAs, some of which have only a very tenuous connection to one another. Later on in the book we’ll encounter a range of different ANOVA methods that apply in quite different situations, but for the purposes of this chapter we’ll only consider the simplest form of ANOVA, in which we have several different groups of observations, and we’re interested in finding out whether those groups differ in terms of some outcome variable of interest. This is the question that is addressed by a <strong><em>one-way ANOVA</em></strong>.</p>
<p>The structure of this chapter is as follows: In Section <a href="anova.html#anxifree">10.2</a> I’ll introduce a fictitious data set that we’ll use as a running example throughout the chapter. After introducing the data, I’ll describe the mechanics of how a one-way ANOVA actually works (Section <a href="anova.html#anovaintro">10.3</a>) and then focus on how you can run one in R (Section <a href="anova.html#introduceaov">10.4</a>). These two sections are the core of the chapter. The remainder of the chapter discusses a range of important topics that inevitably arise when running an ANOVA, namely how to calculate effect sizes (Section <a href="anova.html#etasquared">10.5</a>), post hoc tests and corrections for multiple comparisons (Section <a href="multiple-comparisons.html#posthoc">11.1</a>) and the assumptions that ANOVA relies upon (Section <a href="multiple-comparisons.html#anovaassumptions">11.2</a>). We’ll also talk about how to check those assumptions and some of the things you can do if the assumptions are violated (Sections <a href="multiple-comparisons.html#levene">11.3</a> to <a href="multiple-comparisons.html#kruskalwallis">11.6</a>). At the end of the chapter we’ll talk a little about the relationship between ANOVA and other statistical tools (Section <a href="anova.html#anovaandt">10.6</a>).</p>
</div>
</div>
<div id="anxifree" class="section level2" number="10.2">
<h2><span class="header-section-number">10.2</span> An illustrative data set</h2>
<p>Suppose you’ve become involved in a clinical trial in which you are testing a new antidepressant drug called <em>Joyzepam</em>. In order to construct a fair test of the drug’s effectiveness, the study involves three separate drugs to be administered. One is a placebo, and the other is an existing antidepressant / anti-anxiety drug called <em>Anxifree</em>. A collection of 18 participants with moderate to severe depression are recruited for your initial testing. Because the drugs are sometimes administered in conjunction with psychological therapy, your study includes 9 people undergoing cognitive behavioural therapy (CBT) and 9 who are not. Participants are randomly assigned (doubly blinded, of course) a treatment, such that there are 3 CBT people and 3 no-therapy people assigned to each of the 3 drugs. A psychologist assesses the mood of each person after a 3 month run with each drug: and the overall <em>improvement</em> in each person’s mood is assessed on a scale ranging from <span class="math inline">\(-5\)</span> to <span class="math inline">\(+5\)</span>.</p>
<p>With that as the study design, let’s now look at what we’ve got in the data file:</p>
<div class="sourceCode" id="cb859"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb859-1"><a href="anova.html#cb859-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">file.path</span>(projecthome, <span class="st">&quot;data&quot;</span>, <span class="st">&quot;clinicaltrial.Rdata&quot;</span>)) <span class="co"># load data</span></span>
<span id="cb859-2"><a href="anova.html#cb859-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(clin.trial)       </span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    18 obs. of  3 variables:
##  $ drug     : Factor w/ 3 levels &quot;placebo&quot;,&quot;anxifree&quot;,..: 1 1 1 2 2 2 3 3 3 1 ...
##  $ therapy  : Factor w/ 2 levels &quot;no.therapy&quot;,&quot;CBT&quot;: 1 1 1 1 1 1 1 1 1 2 ...
##  $ mood.gain: num  0.5 0.3 0.1 0.6 0.4 0.2 1.4 1.7 1.3 0.6 ...</code></pre>
<p>So we have a single data frame called <code>clin.trial</code>, containing three variables; <code>drug</code>, <code>therapy</code> and <code>mood.gain</code>. Next, let’s print the data frame to get a sense of what the data actually look like.</p>
<div class="sourceCode" id="cb861"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb861-1"><a href="anova.html#cb861-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>( clin.trial )</span></code></pre></div>
<pre><code>##        drug    therapy mood.gain
## 1   placebo no.therapy       0.5
## 2   placebo no.therapy       0.3
## 3   placebo no.therapy       0.1
## 4  anxifree no.therapy       0.6
## 5  anxifree no.therapy       0.4
## 6  anxifree no.therapy       0.2
## 7  joyzepam no.therapy       1.4
## 8  joyzepam no.therapy       1.7
## 9  joyzepam no.therapy       1.3
## 10  placebo        CBT       0.6
## 11  placebo        CBT       0.9
## 12  placebo        CBT       0.3
## 13 anxifree        CBT       1.1
## 14 anxifree        CBT       0.8
## 15 anxifree        CBT       1.2
## 16 joyzepam        CBT       1.8
## 17 joyzepam        CBT       1.3
## 18 joyzepam        CBT       1.4</code></pre>
<p>For the purposes of this chapter, what we’re really interested in is the effect of <code>drug</code> on <code>mood.gain</code>. The first thing to do is calculate some descriptive statistics and draw some graphs. In Chapter <a href="descriptives.html#descriptives">3</a> we discussed a variety of different functions that can be used for this purpose. For instance, we can use the <code>xtabs()</code> function to see how many people we have in each group:</p>
<div class="sourceCode" id="cb863"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb863-1"><a href="anova.html#cb863-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>( <span class="sc">~</span>drug, clin.trial )</span></code></pre></div>
<pre><code>## drug
##  placebo anxifree joyzepam 
##        6        6        6</code></pre>
<p>Similarly, we can use the <code>aggregate()</code> function to calculate means and standard deviations for the <code>mood.gain</code> variable broken down by which <code>drug</code> was administered:</p>
<div class="sourceCode" id="cb865"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb865-1"><a href="anova.html#cb865-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>( mood.gain <span class="sc">~</span> drug, clin.trial, mean )</span></code></pre></div>
<pre><code>##       drug mood.gain
## 1  placebo 0.4500000
## 2 anxifree 0.7166667
## 3 joyzepam 1.4833333</code></pre>
<div class="sourceCode" id="cb867"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb867-1"><a href="anova.html#cb867-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>( mood.gain <span class="sc">~</span> drug, clin.trial, sd )</span></code></pre></div>
<pre><code>##       drug mood.gain
## 1  placebo 0.2810694
## 2 anxifree 0.3920034
## 3 joyzepam 0.2136976</code></pre>
<p>Finally, we can use <code>plotmeans()</code> from the <code>gplots</code> package to produce a pretty picture.</p>
<div class="sourceCode" id="cb869"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb869-1"><a href="anova.html#cb869-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gplots)</span>
<span id="cb869-2"><a href="anova.html#cb869-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plotmeans</span>(  <span class="at">formula =</span> mood.gain <span class="sc">~</span> drug,  <span class="co"># plot mood.gain by drug</span></span>
<span id="cb869-3"><a href="anova.html#cb869-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> clin.trial,           <span class="co"># the data frame</span></span>
<span id="cb869-4"><a href="anova.html#cb869-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">xlab =</span> <span class="st">&quot;Drug Administered&quot;</span>,  <span class="co"># x-axis label</span></span>
<span id="cb869-5"><a href="anova.html#cb869-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">ylab =</span> <span class="st">&quot;Mood Gain&quot;</span>,          <span class="co"># y-axis label</span></span>
<span id="cb869-6"><a href="anova.html#cb869-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">n.label =</span> <span class="cn">FALSE</span>              <span class="co"># don&#39;t display sample size</span></span>
<span id="cb869-7"><a href="anova.html#cb869-7" aria-hidden="true" tabindex="-1"></a> )</span></code></pre></div>
<p>The results are shown in Figure <a href="anova.html#fig:moodgain">10.1</a>, which plots the average mood gain for all three conditions; error bars show 95% confidence intervals. As the plot makes clear, there is a larger improvement in mood for participants in the Joyzepam group than for either the Anxifree group or the placebo group. The Anxifree group shows a larger mood gain than the control group, but the difference isn’t as large.</p>
<p>The question that we want to answer is: are these difference “real,” or are they just due to chance?</p>
<pre><code>## 
## Attaching package: &#39;gplots&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     lowess</code></pre>
<div class="figure"><span style="display:block;" id="fig:moodgain"></span>
<img src="schuster-statistics-remix_files/figure-html/moodgain-1.png" alt="Average mood gain as a function of drug administered. Error bars depict 95% confidence intervals associated with each of the group means." width="672" />
<p class="caption">
Figure 10.1: Average mood gain as a function of drug administered. Error bars depict 95% confidence intervals associated with each of the group means.
</p>
</div>
</div>
<div id="anovaintro" class="section level2" number="10.3">
<h2><span class="header-section-number">10.3</span> How ANOVA works</h2>
<p>In order to answer the question posed by our clinical trial data, we’re going to run a one-way ANOVA. As usual, I’m going to start by showing you how to do it the hard way, building the statistical tool from the ground up and showing you how you could do it in R if you didn’t have access to any of the cool built-in ANOVA functions. And, as always, I hope you’ll read it carefully, try to do it the long way once or twice to make sure you really understand how ANOVA works, and then – once you’ve grasped the concept – never <em>ever</em> do it this way again.</p>
<p>The experimental design that I described in the previous section strongly suggests that we’re interested in comparing the average mood change for the three different drugs. In that sense, we’re talking about an analysis similar to the <span class="math inline">\(t\)</span>-test (Chapter <a href="ttest.html#ttest">9</a>, but involving more than two groups. If we let <span class="math inline">\(\mu_P\)</span> denote the population mean for the mood change induced by the placebo, and let <span class="math inline">\(\mu_A\)</span> and <span class="math inline">\(\mu_J\)</span> denote the corresponding means for our two drugs, Anxifree and Joyzepam, then the (somewhat pessimistic) null hypothesis that we want to test is that all three population means are identical: that is, <em>neither</em> of the two drugs is any more effective than a placebo. Mathematically, we write this null hypothesis like this:
<span class="math display">\[
\begin{array}{rcl}
H_0 &amp;:&amp; \mbox{it is true that } \mu_P = \mu_A = \mu_J
\end{array}
\]</span>
As a consequence, our alternative hypothesis is that at least one of the three different treatments is different from the others. It’s a little trickier to write this mathematically, because (as we’ll discuss) there are quite a few different ways in which the null hypothesis can be false. So for now we’ll just write the alternative hypothesis like this:
<span class="math display">\[
\begin{array}{rcl}
H_1 &amp;:&amp; \mbox{it is *not* true that } \mu_P = \mu_A = \mu_J
\end{array}
\]</span>
This null hypothesis is a lot trickier to test than any of the ones we’ve seen previously. How shall we do it? A sensible guess would be to “do an ANOVA,” since that’s the title of the chapter, but it’s not particularly clear why an “analysis of <em>variances</em>” will help us learn anything useful about the <em>means</em>. In fact, this is one of the biggest conceptual difficulties that people have when first encountering ANOVA. To see how this works, I find it most helpful to start by talking about variances. In fact, what I’m going to do is start by playing some mathematical games with the formula that describes the variance. That is, we’ll start out by playing around with variances, and it will turn out that this gives us a useful tool for investigating means.</p>
<div id="two-formulas-for-the-variance-of-y" class="section level3" number="10.3.1">
<h3><span class="header-section-number">10.3.1</span> Two formulas for the variance of <span class="math inline">\(Y\)</span></h3>
<p>Firstly, let’s start by introducing some notation. We’ll use <span class="math inline">\(G\)</span> to refer to the total number of groups. For our data set, there are three drugs, so there are <span class="math inline">\(G=3\)</span> groups. Next, we’ll use <span class="math inline">\(N\)</span> to refer to the total sample size: there are a total of <span class="math inline">\(N=18\)</span> people in our data set. Similarly, let’s use <span class="math inline">\(N_k\)</span> to denote the number of people in the <span class="math inline">\(k\)</span>-th group. In our fake clinical trial, the sample size is <span class="math inline">\(N_k = 6\)</span> for all three groups.<a href="#fn149" class="footnote-ref" id="fnref149"><sup>149</sup></a> Finally, we’ll use <span class="math inline">\(Y\)</span> to denote the outcome variable: in our case, <span class="math inline">\(Y\)</span> refers to mood change. Specifically, we’ll use <span class="math inline">\(Y_{ik}\)</span> to refer to the mood change experienced by the <span class="math inline">\(i\)</span>-th member of the <span class="math inline">\(k\)</span>-th group. Similarly, we’ll use <span class="math inline">\(\bar{Y}\)</span> to be the average mood change, taken across all 18 people in the experiment, and <span class="math inline">\(\bar{Y}_k\)</span> to refer to the average mood change experienced by the 6 people in group <span class="math inline">\(k\)</span>.</p>
<p>Excellent. Now that we’ve got our notation sorted out, we can start writing down formulas. To start with, let’s recall the formula for the variance that we used in Section <a href="descriptives.html#var">3.4</a>, way back in those kinder days when we were just doing descriptive statistics. The sample variance of <span class="math inline">\(Y\)</span> is defined as follows:
<span class="math display">\[
\mbox{Var}(Y) = \frac{1}{N} \sum_{k=1}^G \sum_{i=1}^{N_k} \left(Y_{ik} - \bar{Y} \right)^2
\]</span>
This formula looks pretty much identical to the formula for the variance in Section <a href="descriptives.html#var">3.4</a>. The only difference is that this time around I’ve got two summations here: I’m summing over groups (i.e., values for <span class="math inline">\(k\)</span>) and over the people within the groups (i.e., values for <span class="math inline">\(i\)</span>). This is purely a cosmetic detail: if I’d instead used the notation <span class="math inline">\(Y_p\)</span> to refer to the value of the outcome variable for person <span class="math inline">\(p\)</span> in the sample, then I’d only have a single summation. The only reason that we have a double summation here is that I’ve classified people into groups, and then assigned numbers to people within groups.</p>
<p>A concrete example might be useful here. Let’s consider this table, in which we have a total of <span class="math inline">\(N=5\)</span> people sorted into <span class="math inline">\(G=2\)</span> groups. Arbitrarily, let’s say that the “cool” people are group 1, and the “uncool” people are group 2, and it turns out that we have three cool people (<span class="math inline">\(N_1 = 3\)</span>) and two uncool people (<span class="math inline">\(N_2 = 2\)</span>).</p>
<table>
<colgroup>
<col width="5%" />
<col width="13%" />
<col width="7%" />
<col width="17%" />
<col width="22%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="left">person (<span class="math inline">\(p\)</span>)</th>
<th align="left">group</th>
<th align="left">group num (<span class="math inline">\(k\)</span>)</th>
<th align="left">index in group (<span class="math inline">\(i\)</span>)</th>
<th align="left">grumpiness (<span class="math inline">\(Y_{ik}\)</span> or <span class="math inline">\(Y_p\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Ann</td>
<td align="left">1</td>
<td align="left">cool</td>
<td align="left">1</td>
<td align="left">1</td>
<td align="left">20</td>
</tr>
<tr class="even">
<td align="left">Ben</td>
<td align="left">2</td>
<td align="left">cool</td>
<td align="left">1</td>
<td align="left">2</td>
<td align="left">55</td>
</tr>
<tr class="odd">
<td align="left">Cat</td>
<td align="left">3</td>
<td align="left">cool</td>
<td align="left">1</td>
<td align="left">3</td>
<td align="left">21</td>
</tr>
<tr class="even">
<td align="left">Dan</td>
<td align="left">4</td>
<td align="left">uncool</td>
<td align="left">2</td>
<td align="left">1</td>
<td align="left">91</td>
</tr>
<tr class="odd">
<td align="left">Egg</td>
<td align="left">5</td>
<td align="left">uncool</td>
<td align="left">2</td>
<td align="left">2</td>
<td align="left">22</td>
</tr>
</tbody>
</table>
<p>Notice that I’ve constructed two different labelling schemes here. We have a “person” variable <span class="math inline">\(p\)</span>, so it would be perfectly sensible to refer to <span class="math inline">\(Y_p\)</span> as the grumpiness of the <span class="math inline">\(p\)</span>-th person in the sample. For instance, the table shows that Dan is the four so we’d say <span class="math inline">\(p = 4\)</span>. So, when talking about the grumpiness <span class="math inline">\(Y\)</span> of this “Dan” person, whoever he might be, we could refer to his grumpiness by saying that <span class="math inline">\(Y_p = 91\)</span>, for person <span class="math inline">\(p = 4\)</span> that is. However, that’s not the only way we could refer to Dan. As an alternative we could note that Dan belongs to the “uncool” group (<span class="math inline">\(k = 2\)</span>), and is in fact the first person listed in the uncool group (<span class="math inline">\(i = 1\)</span>). So it’s equally valid to refer to Dan’s grumpiness by saying that <span class="math inline">\(Y_{ik} = 91\)</span>, where <span class="math inline">\(k = 2\)</span> and <span class="math inline">\(i = 1\)</span>. In other words, each person <span class="math inline">\(p\)</span> corresponds to a unique <span class="math inline">\(ik\)</span> combination, and so the formula that I gave above is actually identical to our original formula for the variance, which would be
<span class="math display">\[
\mbox{Var}(Y) = \frac{1}{N} \sum_{p=1}^N  \left(Y_{p} - \bar{Y} \right)^2
\]</span>
In both formulas, all we’re doing is summing over all of the observations in the sample. Most of the time we would just use the simpler <span class="math inline">\(Y_p\)</span> notation: the equation using <span class="math inline">\(Y_p\)</span> is clearly the simpler of the two. However, when doing an ANOVA it’s important to keep track of which participants belong in which groups, and we need to use the <span class="math inline">\(Y_{ik}\)</span> notation to do this.</p>
</div>
<div id="from-variances-to-sums-of-squares" class="section level3" number="10.3.2">
<h3><span class="header-section-number">10.3.2</span> From variances to sums of squares</h3>
<p>Okay, now that we’ve got a good grasp on how the variance is calculated, let’s define something called the <strong><em>total sum of squares</em></strong>, which is denoted SS<span class="math inline">\(_{tot}\)</span>. This is very simple: instead of averaging the squared deviations, which is what we do when calculating the variance, we just add them up. So the formula for the total sum of squares is almost identical to the formula for the variance:
<span class="math display">\[
\mbox{SS}_{tot} = \sum_{k=1}^G \sum_{i=1}^{N_k} \left(Y_{ik} - \bar{Y} \right)^2
\]</span>
When we talk about analysing variances in the context of ANOVA, what we’re really doing is working with the total sums of squares rather than the actual variance. One very nice thing about the total sum of squares is that we can break it up into two different kinds of variation. Firstly, we can talk about the <strong><em>within-group sum of squares</em></strong>, in which we look to see how different each individual person is from their own group mean:
<span class="math display">\[
\mbox{SS}_w = \sum_{k=1}^G \sum_{i=1}^{N_k} \left( Y_{ik} - \bar{Y}_k \right)^2
\]</span>
where <span class="math inline">\(\bar{Y}_k\)</span> is a group mean. In our example, <span class="math inline">\(\bar{Y}_k\)</span> would be the average mood change experienced by those people given the <span class="math inline">\(k\)</span>-th drug. So, instead of comparing individuals to the average of <em>all</em> people in the experiment, we’re only comparing them to those people in the the same group. As a consequence, you’d expect the value of <span class="math inline">\(\mbox{SS}_w\)</span> to be smaller than the total sum of squares, because it’s completely ignoring any group differences – that is, the fact that the drugs (if they work) will have different effects on people’s moods.</p>
<p>Next, we can define a third notion of variation which captures <em>only</em> the differences between groups. We do this by looking at the differences between the group means <span class="math inline">\(\bar{Y}_k\)</span> and grand mean <span class="math inline">\(\bar{Y}\)</span>. In order to quantify the extent of this variation, what we do is calculate the <strong><em>between-group sum of squares</em></strong>:
<span class="math display">\[
\begin{array}{rcl}
\mbox{SS}_{b} &amp;=&amp; \sum_{k=1}^G \sum_{i=1}^{N_k} \left( \bar{Y}_k - \bar{Y} \right)^2
 \\
&amp;=&amp; \sum_{k=1}^G N_k \left( \bar{Y}_k - \bar{Y} \right)^2
\end{array}
\]</span>
It’s not too difficult to show that the total variation among people in the experiment <span class="math inline">\(\mbox{SS}_{tot}\)</span> is actually the sum of the differences between the groups <span class="math inline">\(\mbox{SS}_b\)</span> and the variation inside the groups <span class="math inline">\(\mbox{SS}_w\)</span>. That is:
<span class="math display">\[
\mbox{SS}_w  + \mbox{SS}_{b} = \mbox{SS}_{tot}
\]</span>
Yay.</p>
<div class="figure"><span style="display:block;" id="fig:anovavara"></span>
<img src="schuster-statistics-remix_files/figure-html/anovavara-1.png" alt="Graphical illustration of &quot;between groups&quot; variation" width="672" />
<p class="caption">
Figure 10.2: Graphical illustration of “between groups” variation
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:anovavarb"></span>
<img src="schuster-statistics-remix_files/figure-html/anovavarb-1.png" alt="Graphical illustration of  &quot;within groups&quot; variation" width="672" />
<p class="caption">
Figure 10.3: Graphical illustration of “within groups” variation
</p>
</div>
<p>Okay, so what have we found out? We’ve discovered that the total variability associated with the outcome variable (<span class="math inline">\(\mbox{SS}_{tot}\)</span>) can be mathematically carved up into the sum of “the variation due to the differences in the sample means for the different groups” (<span class="math inline">\(\mbox{SS}_{b}\)</span>) plus “all the rest of the variation” (<span class="math inline">\(\mbox{SS}_{w}\)</span>). How does that help me find out whether the groups have different population means? Um. Wait. Hold on a second… now that I think about it, this is <em>exactly</em> what we were looking for. If the null hypothesis is true, then you’d expect all the sample means to be pretty similar to each other, right? And that would imply that you’d expect <span class="math inline">\(\mbox{SS}_{b}\)</span> to be really small, or at least you’d expect it to be a lot smaller than the “the variation associated with everything else,” <span class="math inline">\(\mbox{SS}_{w}\)</span>. Hm. I detect a hypothesis test coming on…</p>
</div>
<div id="from-sums-of-squares-to-the-f-test" class="section level3" number="10.3.3">
<h3><span class="header-section-number">10.3.3</span> From sums of squares to the <span class="math inline">\(F\)</span>-test</h3>
<p>As we saw in the last section, the <em>qualitative</em> idea behind ANOVA is to compare the two sums of squares values <span class="math inline">\(\mbox{SS}_b\)</span> and <span class="math inline">\(\mbox{SS}_w\)</span> to each other: if the between-group variation is <span class="math inline">\(\mbox{SS}_b\)</span> is large relative to the within-group variation <span class="math inline">\(\mbox{SS}_w\)</span> then we have reason to suspect that the population means for the different groups aren’t identical to each other. In order to convert this into a workable hypothesis test, there’s a little bit of “fiddling around” needed. What I’ll do is first show you <em>what</em> we do to calculate our test statistic – which is called an <strong><em><span class="math inline">\(F\)</span> ratio</em></strong> – and then try to give you a feel for <em>why</em> we do it this way.</p>
<p>In order to convert our SS values into an <span class="math inline">\(F\)</span>-ratio, the first thing we need to calculate is the <strong><em>degrees of freedom</em></strong> associated with the SS<span class="math inline">\(_b\)</span> and SS<span class="math inline">\(_w\)</span> values. As usual, the degrees of freedom corresponds to the number of unique “data points” that contribute to a particular calculation, minus the number of “constraints” that they need to satisfy. For the within-groups variability, what we’re calculating is the variation of the individual observations (<span class="math inline">\(N\)</span> data points) around the group means (<span class="math inline">\(G\)</span> constraints). In contrast, for the between groups variability, we’re interested in the variation of the group means (<span class="math inline">\(G\)</span> data points) around the grand mean (1 constraint). Therefore, the degrees of freedom here are:
<span class="math display">\[
\begin{array}{lcl}
\mbox{df}_b &amp;=&amp; G-1 \\
\mbox{df}_w &amp;=&amp; N-G \\
\end{array}
\]</span>
Okay, that seems simple enough. What we do next is convert our summed squares value into a “mean squares” value, which we do by dividing by the degrees of freedom:
<span class="math display">\[
\begin{array}{lcl}
\mbox{MS}_b &amp;=&amp; \displaystyle\frac{\mbox{SS}_b }{ \mbox{df}_b} \\
\mbox{MS}_w &amp;=&amp; \displaystyle\frac{\mbox{SS}_w }{ \mbox{df}_w} 
\end{array}
\]</span>
Finally, we calculate the <span class="math inline">\(F\)</span>-ratio by dividing the between-groups MS by the within-groups MS:
<span class="math display">\[
F = \frac{\mbox{MS}_b }{ \mbox{MS}_w } 
\]</span>
At a very general level, the intuition behind the <span class="math inline">\(F\)</span> statistic is straightforward: bigger values of <span class="math inline">\(F\)</span> means that the between-groups variation is large, relative to the within-groups variation. As a consequence, the larger the value of <span class="math inline">\(F\)</span>, the more evidence we have against the null hypothesis. But how large does <span class="math inline">\(F\)</span> have to be in order to actually <em>reject</em> <span class="math inline">\(H_0\)</span>? In order to understand this, you need a slightly deeper understanding of what ANOVA is and what the mean squares values actually are.</p>
<p>The next section discusses that in a bit of detail, but for readers that aren’t interested in the details of what the test is actually measuring, I’ll cut to the chase. In order to complete our hypothesis test, we need to know the sampling distribution for <span class="math inline">\(F\)</span> if the null hypothesis is true. Not surprisingly, the sampling distribution for the <span class="math inline">\(F\)</span> <em>statistic</em> under the null hypothesis is an <span class="math inline">\(F\)</span> <em>distribution</em>. If you recall back to our discussion of the <span class="math inline">\(F\)</span> distribution in Chapter @ref(probability, the <span class="math inline">\(F\)</span> distribution has two parameters, corresponding to the two degrees of freedom involved: the first one df<span class="math inline">\(_1\)</span> is the between groups degrees of freedom df<span class="math inline">\(_b\)</span>, and the second one df<span class="math inline">\(_2\)</span> is the within groups degrees of freedom df<span class="math inline">\(_w\)</span>.</p>
<p>A summary of all the key quantities involved in a one-way ANOVA, including the formulas showing how they are calculated, is shown in Table <a href="anova.html#tab:anovatable">10.1</a>.</p>
<table>
<caption><span id="tab:anovatable">Table 10.1: </span>All of the key quantities involved in an ANOVA, organised into a “standard” ANOVA table. The formulas for all quantities (except the <span class="math inline">\(p\)</span>-value, which has a very ugly formula and would be nightmarishly hard to calculate without a computer) are shown.</caption>
<colgroup>
<col width="7%" />
<col width="9%" />
<col width="32%" />
<col width="23%" />
<col width="19%" />
<col width="6%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">df</th>
<th align="left">sum of squares</th>
<th align="left">mean squares</th>
<th align="left"><span class="math inline">\(F\)</span> statistic</th>
<th align="left"><span class="math inline">\(p\)</span> value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">between groups</td>
<td align="left"><span class="math inline">\(\mbox{df}_b = G-1\)</span></td>
<td align="left">SS<span class="math inline">\(_b = \displaystyle\sum_{k=1}^G N_k (\bar{Y}_k - \bar{Y})^2\)</span></td>
<td align="left"><span class="math inline">\(\mbox{MS}_b = \frac{\mbox{SS}_b}{\mbox{df}_b}\)</span></td>
<td align="left"><span class="math inline">\(F = \frac{\mbox{MS}_b }{ \mbox{MS}_w }\)</span></td>
<td align="left">[complicated]</td>
</tr>
<tr class="even">
<td align="left">within groups</td>
<td align="left"><span class="math inline">\(\mbox{df}_w = N-G\)</span></td>
<td align="left">SS<span class="math inline">\(_w = \sum_{k=1}^G \sum_{i = 1}^{N_k} ( {Y}_{ik} - \bar{Y}_k)^2\)</span></td>
<td align="left"><span class="math inline">\(\mbox{MS}_w = \frac{\mbox{SS}_w}{\mbox{df}_w}\)</span></td>
<td align="left">-</td>
<td align="left">-</td>
</tr>
</tbody>
</table>
</div>
<div id="anovamodel" class="section level3" number="10.3.4">
<h3><span class="header-section-number">10.3.4</span> The model for the data and the meaning of <span class="math inline">\(F\)</span> (advanced)</h3>
<p>At a fundamental level, ANOVA is a competition between two different statistical models, <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_1\)</span>. When I described the null and alternative hypotheses at the start of the section, I was a little imprecise about what these models actually are. I’ll remedy that now, though you probably won’t like me for doing so. If you recall, our null hypothesis was that all of the group means are identical to one another. If so, then a natural way to think about the outcome variable <span class="math inline">\(Y_{ik}\)</span> is to describe individual scores in terms of a single population mean <span class="math inline">\(\mu\)</span>, plus the deviation from that population mean. This deviation is usually denoted <span class="math inline">\(\epsilon_{ik}\)</span> and is traditionally called the <em>error</em> or <strong><em>residual</em></strong> associated with that observation. Be careful though: just like we saw with the word “significant,” the word “error” has a technical meaning in statistics that isn’t quite the same as its everyday English definition. In everyday language, “error” implies a mistake of some kind; in statistics, it doesn’t (or at least, not necessarily). With that in mind, the word “residual” is a better term than the word “error.” In statistics, both words mean “leftover variability”: that is, “stuff” that the model can’t explain. In any case, here’s what the null hypothesis looks like when we write it as a statistical model:
<span class="math display">\[
Y_{ik} = \mu + \epsilon_{ik}
\]</span>
where we make the <em>assumption</em> (discussed later) that the residual values <span class="math inline">\(\epsilon_{ik}\)</span> are normally distributed, with mean 0 and a standard deviation <span class="math inline">\(\sigma\)</span> that is the same for all groups. To use the notation that we introduced in Chapter <a href="#probability"><strong>??</strong></a> we would write this assumption like this:
<span class="math display">\[
\epsilon_{ik} \sim \mbox{Normal}(0, \sigma^2)
\]</span></p>
<p>What about the alternative hypothesis, <span class="math inline">\(H_1\)</span>? The only difference between the null hypothesis and the alternative hypothesis is that we allow each group to have a different population mean. So, if we let <span class="math inline">\(\mu_k\)</span> denote the population mean for the <span class="math inline">\(k\)</span>-th group in our experiment, then the statistical model corresponding to <span class="math inline">\(H_1\)</span> is:
<span class="math display">\[
Y_{ik} = \mu_k + \epsilon_{ik}
\]</span>
where, once again, we assume that the error terms are normally distributed with mean 0 and standard deviation <span class="math inline">\(\sigma\)</span>. That is, the alternative hypothesis also assumes that
<span class="math display">\[
\epsilon \sim \mbox{Normal}(0, \sigma^2)
\]</span></p>
<p>Okay, now that we’ve described the statistical models underpinning <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_1\)</span> in more detail, it’s now pretty straightforward to say what the mean square values are measuring, and what this means for the interpretation of <span class="math inline">\(F\)</span>. I won’t bore you with the proof of this, but it turns out that the within-groups mean square, MS<span class="math inline">\(_w\)</span>, can be viewed as an estimator (in the technical sense: Chapter <a href="inferential-statistics-the-central-limit-theorem.html#estimation">4.2</a> of the error variance <span class="math inline">\(\sigma^2\)</span>. The between-groups mean square MS<span class="math inline">\(_b\)</span> is also an estimator; but what it estimates is the error variance <em>plus</em> a quantity that depends on the true differences among the group means. If we call this quantity <span class="math inline">\(Q\)</span>, then we can see that the <span class="math inline">\(F\)</span>-statistic is basically<a href="#fn150" class="footnote-ref" id="fnref150"><sup>150</sup></a></p>
<p><span class="math display">\[
F = \frac{\hat{Q} + \hat\sigma^2}{\hat\sigma^2}
\]</span>
where the true value <span class="math inline">\(Q=0\)</span> if the null hypothesis is true, and <span class="math inline">\(Q &gt; 0\)</span> if the alternative hypothesis is true <span class="citation">(e.g. ch. 10 <a href="#ref-Hays1994" role="doc-biblioref">Hays 1994</a>)</span>. Therefore, at a bare minimum <em>the <span class="math inline">\(F\)</span> value must be larger than 1</em> to have any chance of rejecting the null hypothesis. Note that this <em>doesn’t</em> mean that it’s impossible to get an <span class="math inline">\(F\)</span>-value less than 1. What it means is that, if the null hypothesis is true the sampling distribution of the <span class="math inline">\(F\)</span> ratio has a mean of 1,<a href="#fn151" class="footnote-ref" id="fnref151"><sup>151</sup></a> and so we need to see <span class="math inline">\(F\)</span>-values larger than 1 in order to safely reject the null.</p>
<p>To be a bit more precise about the sampling distribution, notice that if the null hypothesis is true, both MS<span class="math inline">\(_b\)</span> and MS<span class="math inline">\(_w\)</span> are estimators of the variance of the residuals <span class="math inline">\(\epsilon_{ik}\)</span>. If those residuals are normally distributed, then you might suspect that the estimate of the variance of <span class="math inline">\(\epsilon_{ik}\)</span> is chi-square distributed… because (as discussed in Section <a href="#otherdists"><strong>??</strong></a> that’s what a chi-square distribution <em>is</em>: it’s what you get when you square a bunch of normally-distributed things and add them up. And since the <span class="math inline">\(F\)</span> distribution is (again, by definition) what you get when you take the ratio between two things that are <span class="math inline">\(\chi^2\)</span> distributed… we have our sampling distribution. Obviously, I’m glossing over a whole lot of stuff when I say this, but in broad terms, this really is where our sampling distribution comes from.</p>
</div>
<div id="anovacalc" class="section level3" number="10.3.5">
<h3><span class="header-section-number">10.3.5</span> A worked example</h3>
<p>The previous discussion was fairly abstract, and a little on the technical side, so I think that at this point it might be useful to see a worked example. For that, let’s go back to the clinical trial data that I introduced at the start of the chapter. The descriptive statistics that we calculated at the beginning tell us our group means: an average mood gain of 0.45 for the placebo, 0.72 for Anxifree, and 1.48 for Joyzepam. With that in mind, let’s party like it’s 1899<a href="#fn152" class="footnote-ref" id="fnref152"><sup>152</sup></a> and start doing some pencil and paper calculations. I’ll only do this for the first 5 observations, because it’s not bloody 1899 and I’m very lazy. Let’s start by calculating <span class="math inline">\(\mbox{SS}_{w}\)</span>, the within-group sums of squares. First, let’s draw up a nice table to help us with our calculations…</p>
<table>
<thead>
<tr class="header">
<th align="left">group (<span class="math inline">\(k\)</span>)</th>
<th align="left">outcome (<span class="math inline">\(Y_{ik}\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">placebo</td>
<td align="left">0.5</td>
</tr>
<tr class="even">
<td align="left">placebo</td>
<td align="left">0.3</td>
</tr>
<tr class="odd">
<td align="left">placebo</td>
<td align="left">0.1</td>
</tr>
<tr class="even">
<td align="left">anxifree</td>
<td align="left">0.6</td>
</tr>
<tr class="odd">
<td align="left">anxifree</td>
<td align="left">0.4</td>
</tr>
</tbody>
</table>
<p>At this stage, the only thing I’ve included in the table is the raw data itself: that is, the grouping variable (i.e., <code>drug</code>) and outcome variable (i.e. <code>mood.gain</code>) for each person. Note that the outcome variable here corresponds to the <span class="math inline">\(Y_{ik}\)</span> value in our equation previously. The next step in the calculation is to write down, for each person in the study, the corresponding group mean; that is, <span class="math inline">\(\bar{Y}_k\)</span>. This is slightly repetitive, but not particularly difficult since we already calculated those group means when doing our descriptive statistics:</p>
<table>
<thead>
<tr class="header">
<th align="left">group (<span class="math inline">\(k\)</span>)</th>
<th align="left">outcome (<span class="math inline">\(Y_{ik}\)</span>)</th>
<th align="left"><strong>group mean</strong> (<span class="math inline">\(\bar{Y}_k\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">placebo</td>
<td align="left">0.5</td>
<td align="left"><strong>0.45</strong></td>
</tr>
<tr class="even">
<td align="left">placebo</td>
<td align="left">0.3</td>
<td align="left"><strong>0.45</strong></td>
</tr>
<tr class="odd">
<td align="left">placebo</td>
<td align="left">0.1</td>
<td align="left"><strong>0.45</strong></td>
</tr>
<tr class="even">
<td align="left">anxifree</td>
<td align="left">0.6</td>
<td align="left"><strong>0.72</strong></td>
</tr>
<tr class="odd">
<td align="left">anxifree</td>
<td align="left">0.4</td>
<td align="left"><strong>0.72</strong></td>
</tr>
</tbody>
</table>
<p>Now that we’ve written those down, we need to calculate – again for every person – the deviation from the corresponding group mean. That is, we want to subtract <span class="math inline">\(Y_{ik} - \bar{Y}_k\)</span>. After we’ve done that, we need to square everything. When we do that, here’s what we get:</p>
<table>
<colgroup>
<col width="7%" />
<col width="12%" />
<col width="15%" />
<col width="32%" />
<col width="32%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">group (<span class="math inline">\(k\)</span>)</th>
<th align="left">outcome (<span class="math inline">\(Y_{ik}\)</span>)</th>
<th align="left">group mean (<span class="math inline">\(\bar{Y}_k\)</span>)</th>
<th align="left"><strong>dev. from group mean</strong> (<span class="math inline">\(Y_{ik} - \bar{Y}_{k}\)</span>)</th>
<th align="left"><strong>squared deviation</strong> (<span class="math inline">\((Y_{ik} - \bar{Y}_{k})^2\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">placebo</td>
<td align="left">0.5</td>
<td align="left">0.45</td>
<td align="left"><strong>0.05</strong></td>
<td align="left"><strong>0.0025</strong></td>
</tr>
<tr class="even">
<td align="left">placebo</td>
<td align="left">0.3</td>
<td align="left">0.45</td>
<td align="left"><strong>-0.15</strong></td>
<td align="left"><strong>0.0225</strong></td>
</tr>
<tr class="odd">
<td align="left">placebo</td>
<td align="left">0.1</td>
<td align="left">0.45</td>
<td align="left"><strong>-0.35</strong></td>
<td align="left"><strong>0.1225</strong></td>
</tr>
<tr class="even">
<td align="left">anxifree</td>
<td align="left">0.6</td>
<td align="left">0.72</td>
<td align="left"><strong>-0.12</strong></td>
<td align="left"><strong>0.0136</strong></td>
</tr>
<tr class="odd">
<td align="left">anxifree</td>
<td align="left">0.4</td>
<td align="left">0.72</td>
<td align="left"><strong>-0.32</strong></td>
<td align="left"><strong>0.1003</strong></td>
</tr>
</tbody>
</table>
<p>The last step is equally straightforward. In order to calculate the within-group sum of squares, we just add up the squared deviations across all observations:
<span class="math display">\[
\begin{array}{rcl}
\mbox{SS}_w &amp;=&amp; 0.0025 + 0.0225 + 0.1225 + 0.0136 + 0.1003 \\
&amp;=&amp; 0.2614
\end{array}
\]</span></p>
<p>Of course, if we actually wanted to get the <em>right</em> answer, we’d need to do this for all 18 observations in the data set, not just the first five. We could continue with the pencil and paper calculations if we wanted to, but it’s pretty tedious. Alternatively, it’s not too hard to get R to do it. Here’s how:</p>
<div class="sourceCode" id="cb872"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb872-1"><a href="anova.html#cb872-1" aria-hidden="true" tabindex="-1"></a>outcome <span class="ot">&lt;-</span> clin.trial<span class="sc">$</span>mood.gain</span>
<span id="cb872-2"><a href="anova.html#cb872-2" aria-hidden="true" tabindex="-1"></a>group <span class="ot">&lt;-</span> clin.trial<span class="sc">$</span>drug</span>
<span id="cb872-3"><a href="anova.html#cb872-3" aria-hidden="true" tabindex="-1"></a>gp.means <span class="ot">&lt;-</span> <span class="fu">tapply</span>(outcome,group,mean)</span>
<span id="cb872-4"><a href="anova.html#cb872-4" aria-hidden="true" tabindex="-1"></a>gp.means <span class="ot">&lt;-</span> gp.means[group]</span>
<span id="cb872-5"><a href="anova.html#cb872-5" aria-hidden="true" tabindex="-1"></a>dev.from.gp.means <span class="ot">&lt;-</span> outcome <span class="sc">-</span> gp.means</span>
<span id="cb872-6"><a href="anova.html#cb872-6" aria-hidden="true" tabindex="-1"></a>squared.devs <span class="ot">&lt;-</span> dev.from.gp.means <span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<p>It might not be obvious from inspection what these commands are doing: as a general rule, the human brain seems to just shut down when faced with a big block of programming. However, I strongly suggest that – if you’re like me and tend to find that the mere sight of this code makes you want to look away and see if there’s any beer left in the fridge or a game of footy on the telly – you take a moment and look closely at these commands one at a time. Every single one of these commands is something you’ve seen before somewhere else in the book. There’s nothing novel about them (though I’ll have to admit that the <code>tapply()</code> function takes a while to get a handle on), so if you’re not quite sure how these commands work, this might be a good time to try playing around with them yourself, to try to get a sense of what’s happening. On the other hand, if this does seem to make sense, then you won’t be all that surprised at what happens when I wrap these variables in a data frame, and print it out…</p>
<div class="sourceCode" id="cb873"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb873-1"><a href="anova.html#cb873-1" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="fu">data.frame</span>( group, outcome, gp.means,</span>
<span id="cb873-2"><a href="anova.html#cb873-2" aria-hidden="true" tabindex="-1"></a>                  dev.from.gp.means, squared.devs )</span>
<span id="cb873-3"><a href="anova.html#cb873-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Y, <span class="at">digits =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##       group outcome gp.means dev.from.gp.means squared.devs
## 1   placebo     0.5     0.45             0.050       0.0025
## 2   placebo     0.3     0.45            -0.150       0.0225
## 3   placebo     0.1     0.45            -0.350       0.1225
## 4  anxifree     0.6     0.72            -0.117       0.0136
## 5  anxifree     0.4     0.72            -0.317       0.1003
## 6  anxifree     0.2     0.72            -0.517       0.2669
## 7  joyzepam     1.4     1.48            -0.083       0.0069
## 8  joyzepam     1.7     1.48             0.217       0.0469
## 9  joyzepam     1.3     1.48            -0.183       0.0336
## 10  placebo     0.6     0.45             0.150       0.0225
## 11  placebo     0.9     0.45             0.450       0.2025
## 12  placebo     0.3     0.45            -0.150       0.0225
## 13 anxifree     1.1     0.72             0.383       0.1469
## 14 anxifree     0.8     0.72             0.083       0.0069
## 15 anxifree     1.2     0.72             0.483       0.2336
## 16 joyzepam     1.8     1.48             0.317       0.1003
## 17 joyzepam     1.3     1.48            -0.183       0.0336
## 18 joyzepam     1.4     1.48            -0.083       0.0069</code></pre>
<p>If you compare this output to the contents of the table I’ve been constructing by hand, you can see that R has done exactly the same calculations that I was doing, and much faster too. So, if we want to finish the calculations of the within-group sum of squares in R, we just ask for the <code>sum()</code> of the <code>squared.devs</code> variable:</p>
<div class="sourceCode" id="cb875"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb875-1"><a href="anova.html#cb875-1" aria-hidden="true" tabindex="-1"></a>SSw <span class="ot">&lt;-</span> <span class="fu">sum</span>( squared.devs )</span>
<span id="cb875-2"><a href="anova.html#cb875-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>( SSw )</span></code></pre></div>
<pre><code>## [1] 1.391667</code></pre>
<p>Obviously, this isn’t the same as what I calculated, because R used all 18 observations. But if I’d typed <code>sum( squared.devs[1:5] )</code> instead, it would have given the same answer that I got earlier.</p>
<p>Okay. Now that we’ve calculated the within groups variation, <span class="math inline">\(\mbox{SS}_w\)</span>, it’s time to turn our attention to the between-group sum of squares, <span class="math inline">\(\mbox{SS}_b\)</span>. The calculations for this case are very similar. The main difference is that, instead of calculating the differences between an observation <span class="math inline">\(Y_{ik}\)</span> and a group mean <span class="math inline">\(\bar{Y}_k\)</span> for all of the observations, we calculate the differences between the group means <span class="math inline">\(\bar{Y}_k\)</span> and the grand mean <span class="math inline">\(\bar{Y}\)</span> (in this case 0.88) for all of the groups…</p>
<table>
<colgroup>
<col width="8%" />
<col width="17%" />
<col width="15%" />
<col width="24%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">group (<span class="math inline">\(k\)</span>)</th>
<th align="left">group mean (<span class="math inline">\(\bar{Y}_k\)</span>)</th>
<th align="left">grand mean (<span class="math inline">\(\bar{Y}\)</span>)</th>
<th align="left">deviation (<span class="math inline">\(\bar{Y}_{k} - \bar{Y}\)</span>)</th>
<th align="left">squared deviations (<span class="math inline">\((\bar{Y}_{k} - \bar{Y})^2\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">placebo</td>
<td align="left">0.45</td>
<td align="left">0.88</td>
<td align="left">-0.43</td>
<td align="left">0.18</td>
</tr>
<tr class="even">
<td align="left">anxifree</td>
<td align="left">0.72</td>
<td align="left">0.88</td>
<td align="left">-0.16</td>
<td align="left">0.03</td>
</tr>
<tr class="odd">
<td align="left">joyzepam</td>
<td align="left">1.48</td>
<td align="left">0.88</td>
<td align="left">0.60</td>
<td align="left">0.36</td>
</tr>
</tbody>
</table>
<p>However, for the between group calculations we need to multiply each of these squared deviations by <span class="math inline">\(N_k\)</span>, the number of observations in the group. We do this because every <em>observation</em> in the group (all <span class="math inline">\(N_k\)</span> of them) is associated with a between group difference. So if there are six people in the placebo group, and the placebo group mean differs from the grand mean by 0.19, then the <em>total</em> between group variation associated with these six people is <span class="math inline">\(6 \times 0.16 = 1.14\)</span>. So we have to extend our little table of calculations…</p>
<table>
<colgroup>
<col width="8%" />
<col width="36%" />
<col width="14%" />
<col width="40%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">group (<span class="math inline">\(k\)</span>)</th>
<th align="left">squared deviations (<span class="math inline">\((\bar{Y}_{k} - \bar{Y})^2\)</span>)</th>
<th align="left">sample size (<span class="math inline">\(N_k\)</span>)</th>
<th align="left">weighted squared dev (<span class="math inline">\(N_k (\bar{Y}_{k} - \bar{Y})^2\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">placebo</td>
<td align="left">0.18</td>
<td align="left">6</td>
<td align="left">1.11</td>
</tr>
<tr class="even">
<td align="left">anxifree</td>
<td align="left">0.03</td>
<td align="left">6</td>
<td align="left">0.16</td>
</tr>
<tr class="odd">
<td align="left">joyzepam</td>
<td align="left">0.36</td>
<td align="left">6</td>
<td align="left">2.18</td>
</tr>
</tbody>
</table>
<p>And so now our between group sum of squares is obtained by summing these “weighted squared deviations” over all three groups in the study:
<span class="math display">\[
\begin{array}{rcl}
\mbox{SS}_{b} &amp;=&amp; 1.11 + 0.16 + 2.18 \\
&amp;=&amp; 3.45
\end{array}
\]</span>
As you can see, the between group calculations are a lot shorter, so you probably wouldn’t usually want to bother using R as your calculator. However, if you <em>did</em> decide to do so, here’s one way you could do it:</p>
<div class="sourceCode" id="cb877"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb877-1"><a href="anova.html#cb877-1" aria-hidden="true" tabindex="-1"></a>gp.means <span class="ot">&lt;-</span> <span class="fu">tapply</span>(outcome,group,mean)</span>
<span id="cb877-2"><a href="anova.html#cb877-2" aria-hidden="true" tabindex="-1"></a>grand.mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(outcome)</span>
<span id="cb877-3"><a href="anova.html#cb877-3" aria-hidden="true" tabindex="-1"></a>dev.from.grand.mean <span class="ot">&lt;-</span> gp.means <span class="sc">-</span> grand.mean</span>
<span id="cb877-4"><a href="anova.html#cb877-4" aria-hidden="true" tabindex="-1"></a>squared.devs <span class="ot">&lt;-</span> dev.from.grand.mean <span class="sc">^</span><span class="dv">2</span></span>
<span id="cb877-5"><a href="anova.html#cb877-5" aria-hidden="true" tabindex="-1"></a>gp.sizes <span class="ot">&lt;-</span> <span class="fu">tapply</span>(outcome,group,length)</span>
<span id="cb877-6"><a href="anova.html#cb877-6" aria-hidden="true" tabindex="-1"></a>wt.squared.devs <span class="ot">&lt;-</span> gp.sizes <span class="sc">*</span> squared.devs</span></code></pre></div>
<p>Again, I won’t actually try to explain this code line by line, but – just like last time – there’s nothing in there that we haven’t seen in several places elsewhere in the book, so I’ll leave it as an exercise for you to make sure you understand it. Once again, we can dump all our variables into a data frame so that we can print it out as a nice table:</p>
<div class="sourceCode" id="cb878"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb878-1"><a href="anova.html#cb878-1" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="fu">data.frame</span>( gp.means, grand.mean, dev.from.grand.mean, </span>
<span id="cb878-2"><a href="anova.html#cb878-2" aria-hidden="true" tabindex="-1"></a>                  squared.devs, gp.sizes, wt.squared.devs )</span>
<span id="cb878-3"><a href="anova.html#cb878-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Y, <span class="at">digits =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##          gp.means grand.mean dev.from.grand.mean squared.devs gp.sizes
## placebo      0.45       0.88               -0.43        0.188        6
## anxifree     0.72       0.88               -0.17        0.028        6
## joyzepam     1.48       0.88                0.60        0.360        6
##          wt.squared.devs
## placebo             1.13
## anxifree            0.17
## joyzepam            2.16</code></pre>
<p>Clearly, these are basically the same numbers that we got before. There are a few tiny differences, but that’s only because the hand-calculated versions have some small errors caused by the fact that I rounded all my numbers to 2 decimal places at each step in the calculations, whereas R only does it at the end (obviously, R s version is more accurate). Anyway, here’s the R command showing the final step:</p>
<div class="sourceCode" id="cb880"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb880-1"><a href="anova.html#cb880-1" aria-hidden="true" tabindex="-1"></a>SSb <span class="ot">&lt;-</span> <span class="fu">sum</span>( wt.squared.devs )</span>
<span id="cb880-2"><a href="anova.html#cb880-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>( SSb )</span></code></pre></div>
<pre><code>## [1] 3.453333</code></pre>
<p>which is (ignoring the slight differences due to rounding error) the same answer that I got when doing things by hand.</p>
<p>Now that we’ve calculated our sums of squares values, <span class="math inline">\(\mbox{SS}_b\)</span> and <span class="math inline">\(\mbox{SS}_w\)</span>, the rest of the ANOVA is pretty painless. The next step is to calculate the degrees of freedom. Since we have <span class="math inline">\(G = 3\)</span> groups and <span class="math inline">\(N = 18\)</span> observations in total, our degrees of freedom can be calculated by simple subtraction:
<span class="math display">\[
\begin{array}{lclcl}
\mbox{df}_b &amp;=&amp; G - 1 &amp;=&amp; 2 \\
\mbox{df}_w &amp;=&amp; N - G &amp;=&amp; 15 
\end{array}
\]</span>
Next, since we’ve now calculated the values for the sums of squares and the degrees of freedom, for both the within-groups variability and the between-groups variability, we can obtain the mean square values by dividing one by the other:
<span class="math display">\[
\begin{array}{lclclcl}
\mbox{MS}_b &amp;=&amp; \displaystyle\frac{\mbox{SS}_b }{  \mbox{df}_b } &amp;=&amp; \displaystyle\frac{3.45}{ 2}  &amp;=&amp; 1.73
\end{array}
\]</span>
<span class="math display">\[
\begin{array}{lclclcl}
\mbox{MS}_w &amp;=&amp; \displaystyle\frac{\mbox{SS}_w }{  \mbox{df}_w } &amp;=&amp; \displaystyle\frac{1.39}{15} &amp;=&amp; 0.09
\end{array}
\]</span>
We’re almost done. The mean square values can be used to calculate the <span class="math inline">\(F\)</span>-value, which is the test statistic that we’re interested in. We do this by dividing the between-groups MS value by the and within-groups MS value.
<span class="math display">\[
F \ = \ \frac{\mbox{MS}_b }{ \mbox{MS}_w } \ = \ \frac{1.73}{0.09} \ = \ 18.6
\]</span>
Woohooo! This is terribly exciting, yes? Now that we have our test statistic, the last step is to find out whether the test itself gives us a significant result. As discussed in Chapter @ref(hypothesistesting, what we really <em>ought</em> to do is choose an <span class="math inline">\(\alpha\)</span> level (i.e., acceptable Type I error rate) ahead of time, construct our rejection region, etc etc. But in practice it’s just easier to directly calculate the <span class="math inline">\(p\)</span>-value. Back in the “old days,” what we’d do is open up a statistics textbook or something and flick to the back section which would actually have a huge lookup table… that’s how we’d “compute” our <span class="math inline">\(p\)</span>-value, because it’s too much effort to do it any other way. However, since we have access to R, I’ll use the <code>pf()</code> function to do it instead. Now, remember that I explained earlier that the <span class="math inline">\(F\)</span>-test is always one sided? And that we only reject the null hypothesis for very large <span class="math inline">\(F\)</span>-values? That means we’re only interested in the <em>upper tail</em> of the <span class="math inline">\(F\)</span>-distribution. The command that you’d use here would be this…</p>
<div class="sourceCode" id="cb882"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb882-1"><a href="anova.html#cb882-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pf</span>( <span class="fl">18.6</span>, <span class="at">df1 =</span> <span class="dv">2</span>, <span class="at">df2 =</span> <span class="dv">15</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 8.672727e-05</code></pre>
<p>Therefore, our <span class="math inline">\(p\)</span>-value comes to 0.0000867, or <span class="math inline">\(8.67 \times 10^{-5}\)</span> in scientific notation. So, unless we’re being <em>extremely</em> conservative about our Type I error rate, we’re pretty much guaranteed to reject the null hypothesis.</p>
<p>At this point, we’re basically done. Having completed our calculations, it’s traditional to organise all these numbers into an ANOVA table like the one in <a href="mailto:Table@reftab" class="email">Table@reftab</a>:anovatable. For our clinical trial data, the ANOVA table would look like this:</p>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">df</th>
<th align="left">sum of squares</th>
<th align="left">mean squares</th>
<th align="left"><span class="math inline">\(F\)</span>-statistic</th>
<th align="left"><span class="math inline">\(p\)</span>-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">between groups</td>
<td align="left">2</td>
<td align="left">3.45</td>
<td align="left">1.73</td>
<td align="left">18.6</td>
<td align="left"><span class="math inline">\(8.67 \times 10^{-5}\)</span></td>
</tr>
<tr class="even">
<td align="left">within groups</td>
<td align="left">15</td>
<td align="left">1.39</td>
<td align="left">0.09</td>
<td align="left">-</td>
<td align="left">-</td>
</tr>
</tbody>
</table>
<p>These days, you’ll probably never have much reason to want to construct one of these tables yourself, but you <em>will</em> find that almost all statistical software (R included) tends to organise the output of an ANOVA into a table like this, so it’s a good idea to get used to reading them. However, although the software will output a full ANOVA table, there’s almost never a good reason to include the whole table in your write up. A pretty standard way of reporting this result would be to write something like this:</p>
<blockquote>
<p>One-way ANOVA showed a significant effect of drug on mood gain (<span class="math inline">\(F(2,15) = 18.6, p&lt;.001\)</span>).</p>
</blockquote>
<p>Sigh. So much work for one short sentence.</p>
</div>
</div>
<div id="introduceaov" class="section level2" number="10.4">
<h2><span class="header-section-number">10.4</span> Running an ANOVA in R</h2>
<p>I’m pretty sure I know what you’re thinking after reading the last section, <em>especially</em> if you followed my advice and tried typing all the commands in yourself…. doing the ANOVA calculations yourself <em>sucks</em>. There’s quite a lot of calculations that we needed to do along the way, and it would be tedious to have to do this over and over again every time you wanted to do an ANOVA. One possible solution to the problem would be to take all these calculations and turn them into some R functions yourself. You’d still have to do a lot of typing, but at least you’d only have to do it the one time: once you’ve created the functions, you can reuse them over and over again. However, writing your own functions is a lot of work, so this is kind of a last resort. Besides, it’s much better if someone else does all the work for you…</p>
<div id="using-the-aov-function-to-specify-your-anova" class="section level3" number="10.4.1">
<h3><span class="header-section-number">10.4.1</span> Using the <code>aov()</code> function to specify your ANOVA</h3>
<p>To make life easier for you, R provides a function called <code>aov()</code>, which – obviously – is an acronym of “Analysis Of Variance.”<a href="#fn153" class="footnote-ref" id="fnref153"><sup>153</sup></a> If you type <code>?aov</code> and have a look at the help documentation, you’ll see that there are several arguments to the <code>aov()</code> function, but the only two that we’re interested in are <code>formula</code> and <code>data</code>. As we’ve seen in a few places previously, the <code>formula</code> argument is what you use to specify the outcome variable and the grouping variable, and the <code>data</code> argument is what you use to specify the data frame that stores these variables. In other words, to do the same ANOVA that I laboriously calculated in the previous section, I’d use a command like this:</p>
<div class="sourceCode" id="cb884"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb884-1"><a href="anova.html#cb884-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>( <span class="at">formula =</span> mood.gain <span class="sc">~</span> drug, <span class="at">data =</span> clin.trial ) </span></code></pre></div>
<p>Actually, that’s not <em>quite</em> the whole story, as you’ll see as soon as you look at the output from this command, which I’ve hidden for the moment in order to avoid confusing you. Before we go into specifics, I should point out that either of these commands will do the same thing:</p>
<div class="sourceCode" id="cb885"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb885-1"><a href="anova.html#cb885-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>( clin.trial<span class="sc">$</span>mood.gain <span class="sc">~</span> clin.trial<span class="sc">$</span>drug ) </span>
<span id="cb885-2"><a href="anova.html#cb885-2" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>( mood.gain <span class="sc">~</span> drug, clin.trial ) </span></code></pre></div>
<p>In the first command, I didn’t specify a <code>data</code> set, and instead relied on the <code>$</code> operator to tell R how to find the variables. In the second command, I dropped the argument names, which is okay in this case because <code>formula</code> is the first argument to the <code>aov()</code> function, and <code>data</code> is the second one. Regardless of how I specify the ANOVA, I can assign the output of the <code>aov()</code> function to a variable, like this for example:</p>
<div class="sourceCode" id="cb886"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb886-1"><a href="anova.html#cb886-1" aria-hidden="true" tabindex="-1"></a>my.anova <span class="ot">&lt;-</span> <span class="fu">aov</span>( mood.gain <span class="sc">~</span> drug, clin.trial ) </span></code></pre></div>
<p>This is almost always a good thing to do, because there’s <em>lots</em> of useful things that we can do with the <code>my.anova</code> variable. So let’s assume that it’s this last command that I used to specify the ANOVA that I’m trying to run, and as a consequence I have this <code>my.anova</code> variable sitting in my workspace, waiting for me to do something with it…</p>
</div>
<div id="aovobjects" class="section level3" number="10.4.2">
<h3><span class="header-section-number">10.4.2</span> Understanding what the <code>aov()</code> function produces</h3>
<p>Now that we’ve seen how to use the <code>aov()</code> function to create <code>my.anova</code> we’d better have a look at what this variable actually is. The first thing to do is to check to see what class of variable we’ve created, since it’s kind of interesting in this case. When we do that…</p>
<div class="sourceCode" id="cb887"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb887-1"><a href="anova.html#cb887-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( my.anova )</span></code></pre></div>
<pre><code>## [1] &quot;aov&quot; &quot;lm&quot;</code></pre>
<p>… we discover that <code>my.anova</code> actually has <em>two</em> classes! The first class tells us that it’s an <code>aov</code> (analysis of variance) object, but the second tells us that it’s <em>also</em> an <code>lm</code> (linear model) object. Later on, we’ll see that this reflects a pretty deep statistical relationship between ANOVA and regression (Chapter <a href="regression.html#regression">8</a> and it means that any function that exists in R for dealing with regressions can also be applied to <code>aov</code> objects, which is neat; but I’m getting ahead of myself. For now, I want to note that what we’ve created is an <code>aov</code> object, and to also make the point that <code>aov</code> objects are actually rather complicated beasts. I <em>won’t</em> be trying to explain everything about them, since it’s way beyond the scope of an introductory statistics subject, but to give you a tiny hint of some of the stuff that R stores inside an <code>aov</code> object, let’s ask it to print out the <code>names()</code> of all the stored quantities…</p>
<div class="sourceCode" id="cb889"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb889-1"><a href="anova.html#cb889-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>( my.anova )</span></code></pre></div>
<pre><code>##  [1] &quot;coefficients&quot;  &quot;residuals&quot;     &quot;effects&quot;       &quot;rank&quot;         
##  [5] &quot;fitted.values&quot; &quot;assign&quot;        &quot;qr&quot;            &quot;df.residual&quot;  
##  [9] &quot;contrasts&quot;     &quot;xlevels&quot;       &quot;call&quot;          &quot;terms&quot;        
## [13] &quot;model&quot;</code></pre>
<p>As we go through the rest of the book, I hope that a few of these will become a little more obvious to you, but right now that’s going to look pretty damned opaque. That’s okay. You don’t need to know any of the details about it right now, and most of it you don’t need at all… what you <em>do</em> need to understand is that the <code>aov()</code> function does a lot of calculations for you, not just the basic ones that I outlined in the previous sections. What this means is that it’s generally a good idea to create a variable like <code>my.anova</code> that stores the output of the <code>aov()</code> function… because later on, you can use <code>my.anova</code> as an input to lots of other functions: those other functions can pull out bits and pieces from the <code>aov</code> object, and calculate various other things that you might need.</p>
<p>Right then. The simplest thing you can do with an <code>aov</code> object is to <code>print()</code> it out. When we do that, it shows us a few of the key quantities of interest:</p>
<div class="sourceCode" id="cb891"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb891-1"><a href="anova.html#cb891-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>( my.anova )</span></code></pre></div>
<pre><code>## Call:
##    aov(formula = mood.gain ~ drug, data = clin.trial)
## 
## Terms:
##                     drug Residuals
## Sum of Squares  3.453333  1.391667
## Deg. of Freedom        2        15
## 
## Residual standard error: 0.3045944
## Estimated effects may be unbalanced</code></pre>
<p>Specificially, it prints out a reminder of the command that you used when you called <code>aov()</code> in the first place, shows you the sums of squares values, the degrees of freedom, and a couple of other quantities that we’re not really interested in right now. Notice, however, that R doesn’t use the names “between-group” and “within-group.” Instead, it tries to assign more meaningful names: in our particular example, the <em>between groups</em> variance corresponds to the effect that the <code>drug</code> has on the outcome variable; and the <em>within groups</em> variance is corresponds to the “leftover” variability, so it calls that the <em>residuals</em>. If we compare these numbers to the numbers that I calculated by hand in Section <a href="anova.html#anovacalc">10.3.5</a>, you can see that they’re identical… the between groups sums of squares is <span class="math inline">\(\mbox{SS}_b = 3.45\)</span>, the within groups sums of squares is <span class="math inline">\(\mbox{SS}_w = 1.39\)</span>, and the degrees of freedom are 2 and 15 repectively.</p>
</div>
<div id="running-the-hypothesis-tests-for-the-anova" class="section level3" number="10.4.3">
<h3><span class="header-section-number">10.4.3</span> Running the hypothesis tests for the ANOVA</h3>
<p>Okay, so we’ve verified that <code>my.anova</code> seems to be storing a bunch of the numbers that we’re looking for, but the <code>print()</code> function didn’t quite give us the output that we really wanted. Where’s the <span class="math inline">\(F\)</span>-value? The <span class="math inline">\(p\)</span>-value? These are the most important numbers in our hypothesis test, but the <code>print()</code> function doesn’t provide them. To get those numbers, we need to use a different function. Instead of asking R to <code>print()</code> out the <code>aov</code> object, we should have asked for a <code>summary()</code> of it.<a href="#fn154" class="footnote-ref" id="fnref154"><sup>154</sup></a> When we do that…</p>
<div class="sourceCode" id="cb893"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb893-1"><a href="anova.html#cb893-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>( my.anova )</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## drug         2  3.453  1.7267   18.61 8.65e-05 ***
## Residuals   15  1.392  0.0928                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>… we get all of the key numbers that we calculated earlier. We get the sums of squares, the degrees of freedom, the mean squares, the <span class="math inline">\(F\)</span>-statistic, and the <span class="math inline">\(p\)</span>-value itself. These are all identical to the numbers that we calculated ourselves when doing it the long and tedious way, and it’s even organised into the same kind of ANOVA table that I showed in Table <a href="anova.html#tab:anovatable">10.1</a>, and then filled out by hand in Section <a href="anova.html#anovacalc">10.3.5</a>. The only things that are even slightly different is that some of the row and column names are a bit different.</p>
</div>
</div>
<div id="etasquared" class="section level2" number="10.5">
<h2><span class="header-section-number">10.5</span> Effect size</h2>
<p>There’s a few different ways you could measure the effect size in an ANOVA, but the most commonly used measures are <span class="math inline">\(\eta^2\)</span> (<strong><em>eta squared</em></strong>) and partial <span class="math inline">\(\eta^2\)</span>. For a one way analysis of variance they’re identical to each other, so for the moment I’ll just explain <span class="math inline">\(\eta^2\)</span>. The definition of <span class="math inline">\(\eta^2\)</span> is actually really simple:
<span class="math display">\[
\eta^2 = \frac{\mbox{SS}_b}{\mbox{SS}_{tot}}
\]</span>
That’s all it is. So when I look at the ANOVA table above, I see that <span class="math inline">\(\mbox{SS}_b = 3.45\)</span> and <span class="math inline">\(\mbox{SS}_{tot} = 3.45 + 1.39 = 4.84\)</span>. Thus we get an <span class="math inline">\(\eta^2\)</span> value of
<span class="math display">\[
\eta^2 = \frac{3.45}{4.84} = 0.71
\]</span>
The interpretation of <span class="math inline">\(\eta^2\)</span> is equally straightforward: it refers to the proportion of the variability in the outcome variable (<code>mood.gain</code>) that can be explained in terms of the predictor (<code>drug</code>). A value of <span class="math inline">\(\eta^2 = 0\)</span> means that there is no relationship at all between the two, whereas a value of <span class="math inline">\(\eta^2 = 1\)</span> means that the relationship is perfect. Better yet, the <span class="math inline">\(\eta^2\)</span> value is very closely related to a squared correlation (i.e., <span class="math inline">\(r^2\)</span>). So, if you’re trying to figure out whether a particular value of <span class="math inline">\(\eta^2\)</span> is big or small, it’s sometimes useful to remember that
<span class="math display">\[
\eta= \sqrt{\frac{\mbox{SS}_b}{\mbox{SS}_{tot}}}
\]</span>
can be interpreted as if it referred to the <em>magnitude</em> of a Pearson correlation. So in our drugs example, the <span class="math inline">\(\eta^2\)</span> value of .71 corresponds to an <span class="math inline">\(\eta\)</span> value of <span class="math inline">\(\sqrt{.71} = .84\)</span>. If we think about this as being equivalent to a correlation of about .84, we’d conclude that the relationship between <code>drug</code> and <code>mood.gain</code> is strong.</p>
<p>The core packages in R don’t include any functions for calculating <span class="math inline">\(\eta^2\)</span>. However, it’s pretty straightforward to calculate it directly from the numbers in the ANOVA table. In fact, since I’ve already got the <code>SSw</code> and <code>SSb</code> variables lying around from my earlier calculations, I can do this:</p>
<div class="sourceCode" id="cb895"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb895-1"><a href="anova.html#cb895-1" aria-hidden="true" tabindex="-1"></a>SStot <span class="ot">&lt;-</span> SSb <span class="sc">+</span> SSw          <span class="co"># total sums of squares</span></span>
<span id="cb895-2"><a href="anova.html#cb895-2" aria-hidden="true" tabindex="-1"></a>eta.squared <span class="ot">&lt;-</span> SSb <span class="sc">/</span> SStot  <span class="co"># eta-squared value</span></span>
<span id="cb895-3"><a href="anova.html#cb895-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>( eta.squared )</span></code></pre></div>
<pre><code>## [1] 0.7127623</code></pre>
<p>However, since it can be tedious to do this the long way (especially when we start running more complicated ANOVAs, such as those in Chapter <a href="#anova2"><strong>??</strong></a> I’ve included an <code>etaSquared()</code> function in the <code>lsr</code> package which will do it for you. For now, the only argument you need to care about is <code>x</code>, which should be the <code>aov</code> object corresponding to your ANOVA. When we do this, what we get as output is this:</p>
<div class="sourceCode" id="cb897"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb897-1"><a href="anova.html#cb897-1" aria-hidden="true" tabindex="-1"></a><span class="fu">etaSquared</span>( <span class="at">x =</span> my.anova )</span></code></pre></div>
<pre><code>##         eta.sq eta.sq.part
## drug 0.7127623   0.7127623</code></pre>
<p>The output here shows two different numbers. The first one corresponds to the <span class="math inline">\(\eta^2\)</span> statistic, precisely as described above. The second one refers to “partial <span class="math inline">\(\eta^2\)</span>,” which is a somewhat different measure of effect size that I’ll describe later. For the simple ANOVA that we’ve just run, they’re the same number. But this won’t always be true once we start running more complicated ANOVAs.<a href="#fn155" class="footnote-ref" id="fnref155"><sup>155</sup></a></p>
</div>
<div id="anovaandt" class="section level2" number="10.6">
<h2><span class="header-section-number">10.6</span> On the relationship between ANOVA and the Student <span class="math inline">\(t\)</span> test</h2>
<p>There’s one last thing I want to point out before finishing. It’s something that a lot of people find kind of surprising, but it’s worth knowing about: an ANOVA with two groups is identical to the Student <span class="math inline">\(t\)</span>-test. No, really. It’s not just that they are similar, but they are actually equivalent in every meaningful way. I won’t try to prove that this is always true, but I will show you a single concrete demonstration. Suppose that, instead of running an ANOVA on our <code>mood.gain ~ drug</code> model, let’s instead do it using <code>therapy</code> as the predictor. If we run this ANOVA, here’s what we get:</p>
<div class="sourceCode" id="cb899"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb899-1"><a href="anova.html#cb899-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>( <span class="fu">aov</span>( mood.gain <span class="sc">~</span> therapy, <span class="at">data =</span> clin.trial ))</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## therapy      1  0.467  0.4672   1.708   0.21
## Residuals   16  4.378  0.2736</code></pre>
<p>Overall, it looks like there’s no significant effect here at all but, as we’ll see in Chapter @ref(anova2 this is actually a misleading answer! In any case, it’s irrelevant to our current goals: our interest here is in the <span class="math inline">\(F\)</span>-statistic, which is <span class="math inline">\(F(1,16) = 1.71\)</span>, and the <span class="math inline">\(p\)</span>-value, which is .21. Since we only have two groups, I didn’t actually need to resort to an ANOVA, I could have just decided to run a Student <span class="math inline">\(t\)</span>-test. So let’s see what happens when I do that:</p>
<div class="sourceCode" id="cb901"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb901-1"><a href="anova.html#cb901-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>( mood.gain <span class="sc">~</span> therapy, <span class="at">data =</span> clin.trial, <span class="at">var.equal =</span> <span class="cn">TRUE</span> )</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  mood.gain by therapy
## t = -1.3068, df = 16, p-value = 0.2098
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.8449518  0.2005073
## sample estimates:
## mean in group no.therapy        mean in group CBT 
##                0.7222222                1.0444444</code></pre>
<p>Curiously, the <span class="math inline">\(p\)</span>-values are identical: once again we obtain a value of <span class="math inline">\(p = .21\)</span>. But what about the test statistic? Having run a <span class="math inline">\(t\)</span>-test instead of an ANOVA, we get a somewhat different answer, namely <span class="math inline">\(t(16) = -1.3068\)</span>. However, there is a fairly straightforward relationship here. If we square the <span class="math inline">\(t\)</span>-statistic</p>
<div class="sourceCode" id="cb903"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb903-1"><a href="anova.html#cb903-1" aria-hidden="true" tabindex="-1"></a><span class="fl">1.3068</span> <span class="sc">^</span> <span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 1.707726</code></pre>
<p>we get the <span class="math inline">\(F\)</span>-statistic from before.</p>
</div>
<div id="summary-7" class="section level2" number="10.7">
<h2><span class="header-section-number">10.7</span> Summary</h2>
<p>In terms of what we have discussed, the key topics were:</p>
<ul>
<li>The basic logic behind how ANOVA works (Section <a href="anova.html#anovaintro">10.3</a>) and how to run one in R (Section <a href="anova.html#introduceaov">10.4</a>).</li>
<li>How to compute an effect size for an ANOVA (Section <a href="anova.html#etasquared">10.5</a>)</li>
</ul>
<p>As with all of the chapters in this book, there are quite a few different sources that I’ve relied upon, but the one stand-out text that I’ve been most heavily influenced by is <span class="citation"><a href="#ref-Sahai2000" role="doc-biblioref">Sahai and Ageel</a> (<a href="#ref-Sahai2000" role="doc-biblioref">2000</a>)</span>. It’s not a good book for beginners, but it’s an excellent book for more advanced readers who are interested in understanding the mathematics behind ANOVA.</p>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Hays1994" class="csl-entry">
Hays, W. L. 1994. <em>Statistics</em>. 5th ed. Fort Worth, TX: Harcourt Brace.
</div>
<div id="ref-Sahai2000" class="csl-entry">
Sahai, H., and M. I. Ageel. 2000. <em>The Analysis of Variance: Fixed, Random and Mixed Models</em>. Boston: Birkhauser.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="149">
<li id="fn149"><p>When all groups have the same number of observations, the experimental design is said to be “balanced.” Balance isn’t such a big deal for one-way ANOVA, which is the topic of this chapter. It becomes more important when you start doing more complicated ANOVAs.<a href="anova.html#fnref149" class="footnote-back">↩︎</a></p></li>
<li id="fn150"><p>In a later versions I’m intending to expand on this. But because I’m writing in a rush, and am already over my deadlines, I’ll just briefly note that if you read ahead to Chapter <a href="#anova2"><strong>??</strong></a> and look at how the “treatment effect” at level <span class="math inline">\(k\)</span> of a factor is defined in terms of the <span class="math inline">\(\alpha_k\)</span> values (see Section <a href="#interactions"><strong>??</strong></a>), it turns out that <span class="math inline">\(Q\)</span> refers to a weighted mean of the squared treatment effects, <span class="math inline">\(Q=(\sum_{k=1}^G N_k\alpha_k^2)/(G-1)\)</span>.<a href="anova.html#fnref150" class="footnote-back">↩︎</a></p></li>
<li id="fn151"><p>Or, if we want to be sticklers for accuracy, <span class="math inline">\(1 + \frac{2}{df_2 - 2}\)</span>.<a href="anova.html#fnref151" class="footnote-back">↩︎</a></p></li>
<li id="fn152"><p>Or, to be precise, party like “it’s 1899 and we’ve got no friends and nothing better to do with our time than do some calculations that wouldn’t have made any sense in 1899 because ANOVA didn’t exist until about the 1920s.”<a href="anova.html#fnref152" class="footnote-back">↩︎</a></p></li>
<li id="fn153"><p>Actually, it <em>also</em> provides a function called <code>anova()</code>, but that works a bit differently, so let’s just ignore it for now.<a href="anova.html#fnref153" class="footnote-back">↩︎</a></p></li>
<li id="fn154"><p>It’s worth noting that you can get the same result by using the command <code>anova( my.anova )</code>.<a href="anova.html#fnref154" class="footnote-back">↩︎</a></p></li>
<li id="fn155"><p>A potentially important footnote – I wrote the <code>etaSquared()</code> function for the <code>lsr</code> package as a teaching exercise, but like all the other functions in the <code>lsr</code> package it hasn’t been exhaustively tested. As of this writing – <code>lsr</code> package version 0.5 – there is at least one known bug in the code. In some cases at least, it doesn’t work (and can give very silly answers) when you set the <code>weights</code> on the observations to something other than uniform. That doesn’t matter at all for this book, since those kinds of analyses are well beyond the scope, but I haven’t had a chance to revisit the package in a long time; it would probably be wise to be very cautious with the use of this function in any context other than very simple introductory analyses. Thanks to Emil Kirkegaard for finding the bug! (Oh, and while I’m here, there’s an interesting blog post by Daniel Lakens suggesting that eta-squared itself is perhaps not the best measure of effect size in real world data analysis: <a href="http://daniellakens.blogspot.com.au/2015/06/why-you-should-use-omega-squared.html" class="uri">http://daniellakens.blogspot.com.au/2015/06/why-you-should-use-omega-squared.html</a><a href="anova.html#fnref155" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ttest.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="multiple-comparisons.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/09-anova.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["schuster-statistics-remix.pdf", "schuster-statistics-remix.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
